{
 "title": "NDT Dashboard - Parte 1: Visão Geral",
 "tags": [
  "ndt",
  "questdb"
 ],
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "isp",
    "label": "ISP",
    "query": "SELECT DISTINCT\n    CASE\n        WHEN asn IN ('18881', '26599', '27699', '19182', '10429') THEN 'Telefônica'\n        WHEN asn IN ('28573', '4230', '22085') THEN 'Claro'\n        WHEN asn IN ('265303') THEN 'TV Alphaville'\n        WHEN asn IN ('14868') THEN 'COPEL Telecom'\n        WHEN asn IN ('53184') THEN 'INB Telecom'\n        WHEN asn IN ('262907') THEN 'Avato Tecnologia'\n        WHEN asn IN ('61844') THEN 'New Master'\n        WHEN asn IN ('28258') THEN 'Powerline Internet'\n        WHEN asn IN ('273683') THEN 'Desconhecido'\n        WHEN asn IN ('22689') THEN 'Sercomtel'\n        WHEN asn IN ('53062') THEN 'G G Net'\n        WHEN asn IN ('264228') THEN 'Brasil Starlink'\n        WHEN asn IN ('28669') THEN 'America Net'\n        WHEN asn IN ('263645') THEN 'Fixtell Telecom'\n        WHEN asn IN ('266949') THEN 'Divifibra'\n        WHEN asn IN ('262700') THEN 'Efibra Telecom'\n        WHEN asn IN ('28658') THEN 'Gigalink'\n        WHEN asn IN ('262673') THEN 'Lafaiete'\n        WHEN asn IN ('52900') THEN 'Quality Telecom'\n        WHEN asn IN ('263629') THEN 'Celloni'\n        WHEN asn IN ('52940') THEN 'Nemesis'\n        WHEN asn IN ('262671') THEN 'S & M Informática'\n        WHEN asn IN ('28241') THEN 'Viaceu Internet'\n        WHEN asn IN ('53191') THEN 'Plug Telecom'\n        WHEN asn IN ('28263') THEN 'Ensite Brasil'\n        WHEN asn IN ('263072') THEN 'BD Fibra Telecom'\n        WHEN asn IN ('53171') THEN 'Omni Telecom'\n        ELSE as_name\n    END AS __text,\n    CASE\n        WHEN asn IN ('18881', '26599', '27699', '19182', '10429') THEN 'Telefônica'\n        WHEN asn IN ('28573', '4230', '22085') THEN 'Claro'\n        WHEN asn IN ('265303') THEN 'TV Alphaville'\n        WHEN asn IN ('14868') THEN 'COPEL Telecom'\n        WHEN asn IN ('53184') THEN 'INB Telecom'\n        WHEN asn IN ('262907') THEN 'Avato Tecnologia'\n        WHEN asn IN ('61844') THEN 'New Master'\n        WHEN asn IN ('28258') THEN 'Powerline Internet'\n        WHEN asn IN ('273683') THEN 'Desconhecido'\n        WHEN asn IN ('22689') THEN 'Sercomtel'\n        WHEN asn IN ('53062') THEN 'G G Net'\n        WHEN asn IN ('264228') THEN 'Brasil Starlink'\n        WHEN asn IN ('28669') THEN 'America Net'\n        WHEN asn IN ('263645') THEN 'Fixtell Telecom'\n        WHEN asn IN ('266949') THEN 'Divifibra'\n        WHEN asn IN ('262700') THEN 'Efibra Telecom'\n        WHEN asn IN ('28658') THEN 'Gigalink'\n        WHEN asn IN ('262673') THEN 'Lafaiete'\n        WHEN asn IN ('52900') THEN 'Quality Telecom'\n        WHEN asn IN ('263629') THEN 'Celloni'\n        WHEN asn IN ('52940') THEN 'Nemesis'\n        WHEN asn IN ('262671') THEN 'S & M Informática'\n        WHEN asn IN ('28241') THEN 'Viaceu Internet'\n        WHEN asn IN ('53191') THEN 'Plug Telecom'\n        WHEN asn IN ('28263') THEN 'Ensite Brasil'\n        WHEN asn IN ('263072') THEN 'BD Fibra Telecom'\n        WHEN asn IN ('53171') THEN 'Omni Telecom'\n        ELSE as_name\n    END AS __value\nFROM client\nORDER BY 1"
   },
   {
    "name": "server",
    "label": "Servidor",
    "query": "SELECT DISTINCT server_site AS __text, server_site AS __value\nFROM download\nWHERE server_site IS NOT NULL\nORDER BY 1"
   }
  ]
 },
 "panels": [
  {
   "title": "Total de Clientes",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(DISTINCT d.client_ip) AS total_clientes\nFROM download d\nJOIN client c ON d.client_ip = c.client_ip\nWHERE $__timeFilter(d.test_time)\n    AND CASE\n        WHEN c.asn IN ('18881', '26599', '27699', '19182', '10429') THEN 'Telefônica'\n        WHEN c.asn IN ('28573', '4230', '22085') THEN 'Claro'\n        WHEN c.asn IN ('265303') THEN 'TV Alphaville'\n        WHEN c.asn IN ('14868') THEN 'COPEL Telecom'\n        WHEN c.asn IN ('53184') THEN 'INB Telecom'\n        WHEN c.asn IN ('262907') THEN 'Avato Tecnologia'\n        WHEN c.asn IN ('61844') THEN 'New Master'\n        WHEN c.asn IN ('28258') THEN 'Powerline Internet'\n        WHEN c.asn IN ('273683') THEN 'Desconhecido'\n        WHEN c.asn IN ('22689') THEN 'Sercomtel'\n        WHEN c.asn IN ('53062') THEN 'G G Net'\n        WHEN c.asn IN ('264228') THEN 'Brasil Starlink'\n        WHEN c.asn IN ('28669') THEN 'America Net'\n        WHEN c.asn IN ('263645') THEN 'Fixtell Telecom'\n        WHEN c.asn IN ('266949') THEN 'Divifibra'\n        WHEN c.asn IN ('262700') THEN 'Efibra Telecom'\n        WHEN c.asn IN ('28658') THEN 'Gigalink'\n        WHEN c.asn IN ('262673') THEN 'Lafaiete'\n        WHEN c.asn IN ('52900') THEN 'Quality Telecom'\n        WHEN c.asn IN ('263629') THEN 'Celloni'\n        WHEN c.asn IN ('52940') THEN 'Nemesis'\n        WHEN c.asn IN ('262671') THEN 'S & M Informática'\n        WHEN c.asn IN ('28241') THEN 'Viaceu Internet'\n        WHEN c.asn IN ('53191') THEN 'Plug Telecom'\n        WHEN c.asn IN ('28263') THEN 'Ensite Brasil'\n        WHEN c.asn IN ('263072') THEN 'BD Fibra Telecom'\n        WHEN c.asn IN ('53171') THEN 'Omni Telecom'\n        ELSE c.as_name\n    END IN ($isp)",
     "selectedFormat": 2
    }
   ]
  },
  {
   "title": "Total de Servidores",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(DISTINCT server_ip) AS total_servidores\nFROM server",
     "selectedFormat": 2
    }
   ]
  },
  {
   "title": "Total de Testes",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count() AS total_testes\nFROM download d\nJOIN client c ON d.client_ip = c.client_ip\nWHERE $__timeFilter(d.test_time)\n    AND CASE\n        WHEN c.asn IN ('18881', '26599', '27699', '19182', '10429') THEN 'Telefônica'\n        WHEN c.asn IN ('28573', '4230', '22085') THEN 'Claro'\n        WHEN c.asn IN ('265303') THEN 'TV Alphaville'\n        WHEN c.asn IN ('14868') THEN 'COPEL Telecom'\n        WHEN c.asn IN ('53184') THEN 'INB Telecom'\n        WHEN c.asn IN ('262907') THEN 'Avato Tecnologia'\n        WHEN c.asn IN ('61844') THEN 'New Master'\n        WHEN c.asn IN ('28258') THEN 'Powerline Internet'\n        WHEN c.asn IN ('273683') THEN 'Desconhecido'\n        WHEN c.asn IN ('22689') THEN 'Sercomtel'\n        WHEN c.asn IN ('53062') THEN 'G G Net'\n        WHEN c.asn IN ('264228') THEN 'Brasil Starlink'\n        WHEN c.asn IN ('28669') THEN 'America Net'\n        WHEN c.asn IN ('263645') THEN 'Fixtell Telecom'\n        WHEN c.asn IN ('266949') THEN 'Divifibra'\n        WHEN c.asn IN ('262700') THEN 'Efibra Telecom'\n        WHEN c.asn IN ('28658') THEN 'Gigalink'\n        WHEN c.asn IN ('262673') THEN 'Lafaiete'\n        WHEN c.asn IN ('52900') THEN 'Quality Telecom'\n        WHEN c.asn IN ('263629') THEN 'Celloni'\n        WHEN c.asn IN ('52940') THEN 'Nemesis'\n        WHEN c.asn IN ('262671') THEN 'S & M Informática'\n        WHEN c.asn IN ('28241') THEN 'Viaceu Internet'\n        WHEN c.asn IN ('53191') THEN 'Plug Telecom'\n        WHEN c.asn IN ('28263') THEN 'Ensite Brasil'\n        WHEN c.asn IN ('263072') THEN 'BD Fibra Telecom'\n        WHEN c.asn IN ('53171') THEN 'Omni Telecom'\n        ELSE c.as_name\n    END IN ($isp)",
     "selectedFormat": 2
    }
   ]
  },
  {
   "title": "Clientes por Provedor",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "rawSql": "SELECT\n    CASE\n        WHEN c.asn IN ('18881', '26599', '27699', '19182', '10429') THEN 'Telefônica'\n        WHEN c.asn IN ('28573', '4230', '22085') THEN 'Claro'\n        WHEN c.asn IN ('265303') THEN 'TV Alphaville'\n        WHEN c.asn IN ('14868') THEN 'COPEL Telecom'\n        WHEN c.asn IN ('53184') THEN 'INB Telecom'\n        WHEN c.asn IN ('262907') THEN 'Avato Tecnologia'\n        WHEN c.asn IN ('61844') THEN 'New Master'\n        WHEN c.asn IN ('28258') THEN 'Powerline Internet'\n        WHEN c.asn IN ('273683') THEN 'Desconhecido'\n        WHEN c.asn IN ('22689') THEN 'Sercomtel'\n        WHEN c.asn IN ('53062') THEN 'G G Net'\n        WHEN c.asn IN ('264228') THEN 'Brasil Starlink'\n        WHEN c.asn IN ('28669') THEN 'America Net'\n        WHEN c.asn IN ('263645') THEN 'Fixtell Telecom'\n        WHEN c.asn IN ('266949') THEN 'Divifibra'\n        WHEN c.asn IN ('262700') THEN 'Efibra Telecom'\n        WHEN c.asn IN ('28658') THEN 'Gigalink'\n        WHEN c.asn IN ('262673') THEN 'Lafaiete'\n        WHEN c.asn IN ('52900') THEN 'Quality Telecom'\n        WHEN c.asn IN ('263629') THEN 'Celloni'\n        WHEN c.asn IN ('52940') THEN 'Nemesis'\n        WHEN c.asn IN ('262671') THEN 'S & M Informática'\n        WHEN c.asn IN ('28241') THEN 'Viaceu Internet'\n        WHEN c.asn IN ('53191') THEN 'Plug Telecom'\n        WHEN c.asn IN ('28263') THEN 'Ensite Brasil'\n        WHEN c.asn IN ('263072') THEN 'BD Fibra Telecom'\n        WHEN c.asn IN ('53171') THEN 'Omni Telecom'\n        ELSE c.as_name\n    END AS provedor,\n    count(DISTINCT d.client_ip) AS total_clientes\nFROM download d\nJOIN client c ON d.client_ip = c.client_ip\nWHERE $__timeFilter(d.test_time)\n    AND CASE\n        WHEN c.asn IN ('18881', '26599', '27699', '19182', '10429') THEN 'Telefônica'\n        WHEN c.asn IN ('28573', '4230', '22085') THEN 'Claro'\n        WHEN c.asn IN ('265303') THEN 'TV Alphaville'\n        WHEN c.asn IN ('14868') THEN 'COPEL Telecom'\n        WHEN c.asn IN ('53184') THEN 'INB Telecom'\n        WHEN c.asn IN ('262907') THEN 'Avato Tecnologia'\n        WHEN c.asn IN ('61844') THEN 'New Master'\n        WHEN c.asn IN ('28258') THEN 'Powerline Internet'\n        WHEN c.asn IN ('273683') THEN 'Desconhecido'\n        WHEN c.asn IN ('22689') THEN 'Sercomtel'\n        WHEN c.asn IN ('53062') THEN 'G G Net'\n        WHEN c.asn IN ('264228') THEN 'Brasil Starlink'\n        WHEN c.asn IN ('28669') THEN 'America Net'\n        WHEN c.asn IN ('263645') THEN 'Fixtell Telecom'\n        WHEN c.asn IN ('266949') THEN 'Divifibra'\n        WHEN c.asn IN ('262700') THEN 'Efibra Telecom'\n        WHEN c.asn IN ('28658') THEN 'Gigalink'\n        WHEN c.asn IN ('262673') THEN 'Lafaiete'\n        WHEN c.asn IN ('52900') THEN 'Quality Telecom'\n        WHEN c.asn IN ('263629') THEN 'Celloni'\n        WHEN c.asn IN ('52940') THEN 'Nemesis'\n        WHEN c.asn IN ('262671') THEN 'S & M Informática'\n        WHEN c.asn IN ('28241') THEN 'Viaceu Internet'\n        WHEN c.asn IN ('53191') THEN 'Plug Telecom'\n        WHEN c.asn IN ('28263') THEN 'Ensite Brasil'\n        WHEN c.asn IN ('263072') THEN 'BD Fibra Telecom'\n        WHEN c.asn IN ('53171') THEN 'Omni Telecom'\n        ELSE c.as_name\n    END IN ($isp)\nGROUP BY provedor\nORDER BY total_clientes DESC\nLIMIT 6",
     "selectedFormat": 2
    }
   ]
  },
  {
   "title": "Mapa Cliente→Servidor",
   "type": "geomap",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT\n    avg(c.latitude) AS lat,\n    avg(c.longitude) AS lon,\n    c.city,\n    c.country_name,\n    t.server_site,\n    CASE\n        WHEN t.server_site = 'aju1916' THEN 1\n        WHEN t.server_site = 'bel1916' THEN 2\n        WHEN t.server_site = 'bsb1916' THEN 3\n        WHEN t.server_site = 'bvb1916' THEN 4\n        WHEN t.server_site = 'cgb1916' THEN 5\n        WHEN t.server_site = 'cgr1916' THEN 6\n        WHEN t.server_site = 'cpv1916' THEN 7\n        WHEN t.server_site = 'cwb10881' THEN 8\n        WHEN t.server_site = 'fln01' THEN 9\n        WHEN t.server_site = 'fln11242' THEN 10\n        WHEN t.server_site = 'for1916' THEN 11\n        WHEN t.server_site = 'gig1916' THEN 12\n        WHEN t.server_site = 'gru02' THEN 13\n        WHEN t.server_site = 'gru03' THEN 14\n        WHEN t.server_site = 'gru07' THEN 15\n        WHEN t.server_site = 'gru15830' THEN 16\n        WHEN t.server_site = 'gru1916' THEN 17\n        WHEN t.server_site = 'gyn1916' THEN 18\n        WHEN t.server_site = 'mao1916' THEN 19\n        WHEN t.server_site = 'mcp1916' THEN 20\n        WHEN t.server_site = 'mcz1916' THEN 21\n        WHEN t.server_site = 'nat1916' THEN 22\n        WHEN t.server_site = 'pmw1916' THEN 23\n        WHEN t.server_site = 'poa2716' THEN 24\n        WHEN t.server_site = 'pvh1916' THEN 25\n        WHEN t.server_site = 'rbr1916' THEN 26\n        WHEN t.server_site = 'rec1916' THEN 27\n        WHEN t.server_site = 'slz1916' THEN 28\n        WHEN t.server_site = 'ssa53164' THEN 29\n        WHEN t.server_site = 'the1916' THEN 30\n        WHEN t.server_site = 'vix1916' THEN 31\n        WHEN t.server_site = 'vix53078' THEN 32\n        ELSE 0\n    END AS server_idx,\n    sum(t.total_testes) AS total_testes\nFROM (\n    SELECT client_ip, server_site, count() AS total_testes\n    FROM download\n    WHERE $__timeFilter(test_time)\n    GROUP BY client_ip, server_site\n) t\nJOIN client c ON t.client_ip = c.client_ip\nWHERE c.country_code = 'BR'\n    AND CASE\n        WHEN c.asn IN ('18881', '26599', '27699', '19182', '10429') THEN 'Telefônica'\n        WHEN c.asn IN ('28573', '4230', '22085') THEN 'Claro'\n        WHEN c.asn IN ('265303') THEN 'TV Alphaville'\n        WHEN c.asn IN ('14868') THEN 'COPEL Telecom'\n        WHEN c.asn IN ('53184') THEN 'INB Telecom'\n        WHEN c.asn IN ('262907') THEN 'Avato Tecnologia'\n        WHEN c.asn IN ('61844') THEN 'New Master'\n        WHEN c.asn IN ('28258') THEN 'Powerline Internet'\n        WHEN c.asn IN ('273683') THEN 'Desconhecido'\n        WHEN c.asn IN ('22689') THEN 'Sercomtel'\n        WHEN c.asn IN ('53062') THEN 'G G Net'\n        WHEN c.asn IN ('264228') THEN 'Brasil Starlink'\n        WHEN c.asn IN ('28669') THEN 'America Net'\n        WHEN c.asn IN ('263645') THEN 'Fixtell Telecom'\n        WHEN c.asn IN ('266949') THEN 'Divifibra'\n        WHEN c.asn IN ('262700') THEN 'Efibra Telecom'\n        WHEN c.asn IN ('28658') THEN 'Gigalink'\n        WHEN c.asn IN ('262673') THEN 'Lafaiete'\n        WHEN c.asn IN ('52900') THEN 'Quality Telecom'\n        WHEN c.asn IN ('263629') THEN 'Celloni'\n        WHEN c.asn IN ('52940') THEN 'Nemesis'\n        WHEN c.asn IN ('262671') THEN 'S & M Informática'\n        WHEN c.asn IN ('28241') THEN 'Viaceu Internet'\n        WHEN c.asn IN ('53191') THEN 'Plug Telecom'\n        WHEN c.asn IN ('28263') THEN 'Ensite Brasil'\n        WHEN c.asn IN ('263072') THEN 'BD Fibra Telecom'\n        WHEN c.asn IN ('53171') THEN 'Omni Telecom'\n        ELSE c.as_name\n    END IN ($isp)\n    AND c.latitude IS NOT NULL\n    AND c.longitude IS NOT NULL\nGROUP BY c.city, c.country_name, t.server_site\nLIMIT 500",
     "selectedFormat": 1
    },
    {
     "rawSql": "SELECT\n    s.latitude AS lat,\n    s.longitude AS lon,\n    s.server_ip,\n    d.server_site,\n    CASE\n        WHEN d.server_site = 'aju1916' THEN 1\n        WHEN d.server_site = 'bel1916' THEN 2\n        WHEN d.server_site = 'bsb1916' THEN 3\n        WHEN d.server_site = 'bvb1916' THEN 4\n        WHEN d.server_site = 'cgb1916' THEN 5\n        WHEN d.server_site = 'cgr1916' THEN 6\n        WHEN d.server_site = 'cpv1916' THEN 7\n        WHEN d.server_site = 'cwb10881' THEN 8\n        WHEN d.server_site = 'fln01' THEN 9\n        WHEN d.server_site = 'fln11242' THEN 10\n        WHEN d.server_site = 'for1916' THEN 11\n        WHEN d.server_site = 'gig1916' THEN 12\n        WHEN d.server_site = 'gru02' THEN 13\n        WHEN d.server_site = 'gru03' THEN 14\n        WHEN d.server_site = 'gru07' THEN 15\n        WHEN d.server_site = 'gru15830' THEN 16\n        WHEN d.server_site = 'gru1916' THEN 17\n        WHEN d.server_site = 'gyn1916' THEN 18\n        WHEN d.server_site = 'mao1916' THEN 19\n        WHEN d.server_site = 'mcp1916' THEN 20\n        WHEN d.server_site = 'mcz1916' THEN 21\n        WHEN d.server_site = 'nat1916' THEN 22\n        WHEN d.server_site = 'pmw1916' THEN 23\n        WHEN d.server_site = 'poa2716' THEN 24\n        WHEN d.server_site = 'pvh1916' THEN 25\n        WHEN d.server_site = 'rbr1916' THEN 26\n        WHEN d.server_site = 'rec1916' THEN 27\n        WHEN d.server_site = 'slz1916' THEN 28\n        WHEN d.server_site = 'ssa53164' THEN 29\n        WHEN d.server_site = 'the1916' THEN 30\n        WHEN d.server_site = 'vix1916' THEN 31\n        WHEN d.server_site = 'vix53078' THEN 32\n        ELSE 0\n    END AS server_idx,\n    s.city,\n    s.country_name,\n    count() AS total_testes,\n    count(DISTINCT d.client_ip) AS clientes_unicos\nFROM download d\nJOIN server s ON d.server_ip = s.server_ip\nWHERE $__timeFilter(d.test_time)\n    AND s.country_code = 'BR'\n    AND s.latitude IS NOT NULL\n    AND s.longitude IS NOT NULL\nGROUP BY s.latitude, s.longitude, s.server_ip, d.server_site, s.city, s.country_name",
     "selectedFormat": 1
    }
   ]
  }
 ]
}