{
 "title": "NDT - Parte 3: Estatisticas por Provedor (Tabelas + Bar Charts)",
 "tags": [
  "ndt",
  "questdb"
 ],
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "isp",
    "label": "ISP",
    "query": "SELECT DISTINCT\n    CASE\n        WHEN asn IN ('18881', '26599', '27699', '19182', '10429') THEN 'Telefônica'\n        WHEN asn IN ('28573', '4230', '22085') THEN 'Claro'\n        WHEN asn IN ('265303') THEN 'TV Alphaville'\n        WHEN asn IN ('14868') THEN 'COPEL Telecom'\n        WHEN asn IN ('53184') THEN 'INB Telecom'\n        WHEN asn IN ('262907') THEN 'Avato Tecnologia'\n        WHEN asn IN ('61844') THEN 'New Master'\n        WHEN asn IN ('28258') THEN 'Powerline Internet'\n        WHEN asn IN ('273683') THEN 'Desconhecido'\n        WHEN asn IN ('22689') THEN 'Sercomtel'\n        WHEN asn IN ('53062') THEN 'G G Net'\n        WHEN asn IN ('264228') THEN 'Brasil Starlink'\n        WHEN asn IN ('28669') THEN 'America Net'\n        WHEN asn IN ('263645') THEN 'Fixtell Telecom'\n        WHEN asn IN ('266949') THEN 'Divifibra'\n        WHEN asn IN ('262700') THEN 'Efibra Telecom'\n        WHEN asn IN ('28658') THEN 'Gigalink'\n        WHEN asn IN ('262673') THEN 'Lafaiete'\n        WHEN asn IN ('52900') THEN 'Quality Telecom'\n        WHEN asn IN ('263629') THEN 'Celloni'\n        WHEN asn IN ('52940') THEN 'Nemesis'\n        WHEN asn IN ('262671') THEN 'S & M Informática'\n        WHEN asn IN ('28241') THEN 'Viaceu Internet'\n        WHEN asn IN ('53191') THEN 'Plug Telecom'\n        WHEN asn IN ('28263') THEN 'Ensite Brasil'\n        WHEN asn IN ('263072') THEN 'BD Fibra Telecom'\n        WHEN asn IN ('53171') THEN 'Omni Telecom'\n        ELSE as_name\n    END AS __text,\n    CASE\n        WHEN asn IN ('18881', '26599', '27699', '19182', '10429') THEN 'Telefônica'\n        WHEN asn IN ('28573', '4230', '22085') THEN 'Claro'\n        WHEN asn IN ('265303') THEN 'TV Alphaville'\n        WHEN asn IN ('14868') THEN 'COPEL Telecom'\n        WHEN asn IN ('53184') THEN 'INB Telecom'\n        WHEN asn IN ('262907') THEN 'Avato Tecnologia'\n        WHEN asn IN ('61844') THEN 'New Master'\n        WHEN asn IN ('28258') THEN 'Powerline Internet'\n        WHEN asn IN ('273683') THEN 'Desconhecido'\n        WHEN asn IN ('22689') THEN 'Sercomtel'\n        WHEN asn IN ('53062') THEN 'G G Net'\n        WHEN asn IN ('264228') THEN 'Brasil Starlink'\n        WHEN asn IN ('28669') THEN 'America Net'\n        WHEN asn IN ('263645') THEN 'Fixtell Telecom'\n        WHEN asn IN ('266949') THEN 'Divifibra'\n        WHEN asn IN ('262700') THEN 'Efibra Telecom'\n        WHEN asn IN ('28658') THEN 'Gigalink'\n        WHEN asn IN ('262673') THEN 'Lafaiete'\n        WHEN asn IN ('52900') THEN 'Quality Telecom'\n        WHEN asn IN ('263629') THEN 'Celloni'\n        WHEN asn IN ('52940') THEN 'Nemesis'\n        WHEN asn IN ('262671') THEN 'S & M Informática'\n        WHEN asn IN ('28241') THEN 'Viaceu Internet'\n        WHEN asn IN ('53191') THEN 'Plug Telecom'\n        WHEN asn IN ('28263') THEN 'Ensite Brasil'\n        WHEN asn IN ('263072') THEN 'BD Fibra Telecom'\n        WHEN asn IN ('53171') THEN 'Omni Telecom'\n        ELSE as_name\n    END AS __value\nFROM client\nORDER BY 1"
   },
   {
    "name": "server",
    "label": "Servidor",
    "query": "SELECT DISTINCT server_site AS __text, server_site AS __value\nFROM download\nWHERE server_site IS NOT NULL\nORDER BY 1"
   }
  ]
 },
 "panels": [
  {
   "title": "Estatísticas de Download por Provedor",
   "type": "table",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Mbps" } },
   "targets": [
    {
     "rawSql": "SELECT * FROM (\n    SELECT\n        CASE\n            WHEN c.asn IN ('18881', '26599', '27699', '19182', '10429') THEN 'Telefônica'\n            WHEN c.asn IN ('28573', '4230', '22085') THEN 'Claro'\n            WHEN c.asn IN ('265303') THEN 'TV Alphaville'\n            WHEN c.asn IN ('14868') THEN 'COPEL Telecom'\n            WHEN c.asn IN ('53184') THEN 'INB Telecom'\n            WHEN c.asn IN ('262907') THEN 'Avato Tecnologia'\n            WHEN c.asn IN ('61844') THEN 'New Master'\n            WHEN c.asn IN ('28258') THEN 'Powerline Internet'\n            WHEN c.asn IN ('273683') THEN 'Desconhecido'\n            WHEN c.asn IN ('22689') THEN 'Sercomtel'\n            WHEN c.asn IN ('53062') THEN 'G G Net'\n            WHEN c.asn IN ('264228') THEN 'Brasil Starlink'\n            WHEN c.asn IN ('28669') THEN 'America Net'\n            WHEN c.asn IN ('263645') THEN 'Fixtell Telecom'\n            WHEN c.asn IN ('266949') THEN 'Divifibra'\n            WHEN c.asn IN ('262700') THEN 'Efibra Telecom'\n            WHEN c.asn IN ('28658') THEN 'Gigalink'\n            WHEN c.asn IN ('262673') THEN 'Lafaiete'\n            WHEN c.asn IN ('52900') THEN 'Quality Telecom'\n            WHEN c.asn IN ('263629') THEN 'Celloni'\n            WHEN c.asn IN ('52940') THEN 'Nemesis'\n            WHEN c.asn IN ('262671') THEN 'S & M Informática'\n            WHEN c.asn IN ('28241') THEN 'Viaceu Internet'\n            WHEN c.asn IN ('53191') THEN 'Plug Telecom'\n            WHEN c.asn IN ('28263') THEN 'Ensite Brasil'\n            WHEN c.asn IN ('263072') THEN 'BD Fibra Telecom'\n            WHEN c.asn IN ('53171') THEN 'Omni Telecom'\n            ELSE c.as_name\n        END AS \"Provedor\",\n        count() AS \"Total de Testes\",\n        count(DISTINCT d.client_ip) AS \"Clientes Únicos\",\n        round(avg(d.mean_throughput_mbps), 2) AS \"Média (Mbps)\",\n        approx_median(d.mean_throughput_mbps) AS \"Mediana (Mbps)\",\n        round(min(d.mean_throughput_mbps), 2) AS \"Mínimo (Mbps)\",\n        round(max(d.mean_throughput_mbps), 2) AS \"Máximo (Mbps)\"\n    FROM download d\n    JOIN client c ON d.client_ip = c.client_ip\n    WHERE $__timeFilter(d.test_time)\n        AND d.mean_throughput_mbps >= 0\n        AND CASE\n            WHEN c.asn IN ('18881', '26599', '27699', '19182', '10429') THEN 'Telefônica'\n            WHEN c.asn IN ('28573', '4230', '22085') THEN 'Claro'\n            WHEN c.asn IN ('265303') THEN 'TV Alphaville'\n            WHEN c.asn IN ('14868') THEN 'COPEL Telecom'\n            WHEN c.asn IN ('53184') THEN 'INB Telecom'\n            WHEN c.asn IN ('262907') THEN 'Avato Tecnologia'\n            WHEN c.asn IN ('61844') THEN 'New Master'\n            WHEN c.asn IN ('28258') THEN 'Powerline Internet'\n            WHEN c.asn IN ('273683') THEN 'Desconhecido'\n            WHEN c.asn IN ('22689') THEN 'Sercomtel'\n            WHEN c.asn IN ('53062') THEN 'G G Net'\n            WHEN c.asn IN ('264228') THEN 'Brasil Starlink'\n            WHEN c.asn IN ('28669') THEN 'America Net'\n            WHEN c.asn IN ('263645') THEN 'Fixtell Telecom'\n            WHEN c.asn IN ('266949') THEN 'Divifibra'\n            WHEN c.asn IN ('262700') THEN 'Efibra Telecom'\n            WHEN c.asn IN ('28658') THEN 'Gigalink'\n            WHEN c.asn IN ('262673') THEN 'Lafaiete'\n            WHEN c.asn IN ('52900') THEN 'Quality Telecom'\n            WHEN c.asn IN ('263629') THEN 'Celloni'\n            WHEN c.asn IN ('52940') THEN 'Nemesis'\n            WHEN c.asn IN ('262671') THEN 'S & M Informática'\n            WHEN c.asn IN ('28241') THEN 'Viaceu Internet'\n            WHEN c.asn IN ('53191') THEN 'Plug Telecom'\n            WHEN c.asn IN ('28263') THEN 'Ensite Brasil'\n            WHEN c.asn IN ('263072') THEN 'BD Fibra Telecom'\n            WHEN c.asn IN ('53171') THEN 'Omni Telecom'\n            ELSE c.as_name\n        END IN ($isp)\n        AND d.server_site IN ($server)\n    GROUP BY \"Provedor\"\n\n    UNION ALL\n\n    SELECT\n        '📊 TOTAL GERAL' AS \"Provedor\",\n        count() AS \"Total de Testes\",\n        count(DISTINCT d.client_ip) AS \"Clientes Únicos\",\n        round(avg(d.mean_throughput_mbps), 2) AS \"Média (Mbps)\",\n        approx_median(d.mean_throughput_mbps) AS \"Mediana (Mbps)\",\n        round(min(d.mean_throughput_mbps), 2) AS \"Mínimo (Mbps)\",\n        round(max(d.mean_throughput_mbps), 2) AS \"Máximo (Mbps)\"\n    FROM download d\n    JOIN client c ON d.client_ip = c.client_ip\n    WHERE $__timeFilter(d.test_time)\n        AND d.mean_throughput_mbps >= 0\n        AND CASE\n            WHEN c.asn IN ('18881', '26599', '27699', '19182', '10429') THEN 'Telefônica'\n            WHEN c.asn IN ('28573', '4230', '22085') THEN 'Claro'\n            WHEN c.asn IN ('265303') THEN 'TV Alphaville'\n            WHEN c.asn IN ('14868') THEN 'COPEL Telecom'\n            WHEN c.asn IN ('53184') THEN 'INB Telecom'\n            WHEN c.asn IN ('262907') THEN 'Avato Tecnologia'\n            WHEN c.asn IN ('61844') THEN 'New Master'\n            WHEN c.asn IN ('28258') THEN 'Powerline Internet'\n            WHEN c.asn IN ('273683') THEN 'Desconhecido'\n            WHEN c.asn IN ('22689') THEN 'Sercomtel'\n            WHEN c.asn IN ('53062') THEN 'G G Net'\n            WHEN c.asn IN ('264228') THEN 'Brasil Starlink'\n            WHEN c.asn IN ('28669') THEN 'America Net'\n            WHEN c.asn IN ('263645') THEN 'Fixtell Telecom'\n            WHEN c.asn IN ('266949') THEN 'Divifibra'\n            WHEN c.asn IN ('262700') THEN 'Efibra Telecom'\n            WHEN c.asn IN ('28658') THEN 'Gigalink'\n            WHEN c.asn IN ('262673') THEN 'Lafaiete'\n            WHEN c.asn IN ('52900') THEN 'Quality Telecom'\n            WHEN c.asn IN ('263629') THEN 'Celloni'\n            WHEN c.asn IN ('52940') THEN 'Nemesis'\n            WHEN c.asn IN ('262671') THEN 'S & M Informática'\n            WHEN c.asn IN ('28241') THEN 'Viaceu Internet'\n            WHEN c.asn IN ('53191') THEN 'Plug Telecom'\n            WHEN c.asn IN ('28263') THEN 'Ensite Brasil'\n            WHEN c.asn IN ('263072') THEN 'BD Fibra Telecom'\n            WHEN c.asn IN ('53171') THEN 'Omni Telecom'\n            ELSE c.as_name\n        END IN ($isp)\n        \n) AS resultado\nORDER BY \"Total de Testes\" DESC",
     "selectedFormat": 1
    }
   ]
  },
  {
   "title": "Estatísticas de Upload por Provedor",
   "type": "table",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Mbps" } },
   "targets": [
    {
     "rawSql": "SELECT * FROM (\n    SELECT\n        CASE\n            WHEN c.asn IN ('18881', '26599', '27699', '19182', '10429') THEN 'Telefônica'\n            WHEN c.asn IN ('28573', '4230', '22085') THEN 'Claro'\n            WHEN c.asn IN ('265303') THEN 'TV Alphaville'\n            WHEN c.asn IN ('14868') THEN 'COPEL Telecom'\n            WHEN c.asn IN ('53184') THEN 'INB Telecom'\n            WHEN c.asn IN ('262907') THEN 'Avato Tecnologia'\n            WHEN c.asn IN ('61844') THEN 'New Master'\n            WHEN c.asn IN ('28258') THEN 'Powerline Internet'\n            WHEN c.asn IN ('273683') THEN 'Desconhecido'\n            WHEN c.asn IN ('22689') THEN 'Sercomtel'\n            WHEN c.asn IN ('53062') THEN 'G G Net'\n            WHEN c.asn IN ('264228') THEN 'Brasil Starlink'\n            WHEN c.asn IN ('28669') THEN 'America Net'\n            WHEN c.asn IN ('263645') THEN 'Fixtell Telecom'\n            WHEN c.asn IN ('266949') THEN 'Divifibra'\n            WHEN c.asn IN ('262700') THEN 'Efibra Telecom'\n            WHEN c.asn IN ('28658') THEN 'Gigalink'\n            WHEN c.asn IN ('262673') THEN 'Lafaiete'\n            WHEN c.asn IN ('52900') THEN 'Quality Telecom'\n            WHEN c.asn IN ('263629') THEN 'Celloni'\n            WHEN c.asn IN ('52940') THEN 'Nemesis'\n            WHEN c.asn IN ('262671') THEN 'S & M Informática'\n            WHEN c.asn IN ('28241') THEN 'Viaceu Internet'\n            WHEN c.asn IN ('53191') THEN 'Plug Telecom'\n            WHEN c.asn IN ('28263') THEN 'Ensite Brasil'\n            WHEN c.asn IN ('263072') THEN 'BD Fibra Telecom'\n            WHEN c.asn IN ('53171') THEN 'Omni Telecom'\n            ELSE c.as_name\n        END AS \"Provedor\",\n        count() AS \"Total de Testes\",\n        count(DISTINCT d.client_ip) AS \"Clientes Únicos\",\n        round(avg(d.mean_throughput_mbps), 2) AS \"Média (Mbps)\",\n        approx_median(d.mean_throughput_mbps) AS \"Mediana (Mbps)\",\n        round(min(d.mean_throughput_mbps), 2) AS \"Mínimo (Mbps)\",\n        round(max(d.mean_throughput_mbps), 2) AS \"Máximo (Mbps)\"\n    FROM upload d\n    JOIN client c ON d.client_ip = c.client_ip\n    WHERE $__timeFilter(d.test_time)\n        AND d.mean_throughput_mbps >= 0\n        AND CASE\n            WHEN c.asn IN ('18881', '26599', '27699', '19182', '10429') THEN 'Telefônica'\n            WHEN c.asn IN ('28573', '4230', '22085') THEN 'Claro'\n            WHEN c.asn IN ('265303') THEN 'TV Alphaville'\n            WHEN c.asn IN ('14868') THEN 'COPEL Telecom'\n            WHEN c.asn IN ('53184') THEN 'INB Telecom'\n            WHEN c.asn IN ('262907') THEN 'Avato Tecnologia'\n            WHEN c.asn IN ('61844') THEN 'New Master'\n            WHEN c.asn IN ('28258') THEN 'Powerline Internet'\n            WHEN c.asn IN ('273683') THEN 'Desconhecido'\n            WHEN c.asn IN ('22689') THEN 'Sercomtel'\n            WHEN c.asn IN ('53062') THEN 'G G Net'\n            WHEN c.asn IN ('264228') THEN 'Brasil Starlink'\n            WHEN c.asn IN ('28669') THEN 'America Net'\n            WHEN c.asn IN ('263645') THEN 'Fixtell Telecom'\n            WHEN c.asn IN ('266949') THEN 'Divifibra'\n            WHEN c.asn IN ('262700') THEN 'Efibra Telecom'\n            WHEN c.asn IN ('28658') THEN 'Gigalink'\n            WHEN c.asn IN ('262673') THEN 'Lafaiete'\n            WHEN c.asn IN ('52900') THEN 'Quality Telecom'\n            WHEN c.asn IN ('263629') THEN 'Celloni'\n            WHEN c.asn IN ('52940') THEN 'Nemesis'\n            WHEN c.asn IN ('262671') THEN 'S & M Informática'\n            WHEN c.asn IN ('28241') THEN 'Viaceu Internet'\n            WHEN c.asn IN ('53191') THEN 'Plug Telecom'\n            WHEN c.asn IN ('28263') THEN 'Ensite Brasil'\n            WHEN c.asn IN ('263072') THEN 'BD Fibra Telecom'\n            WHEN c.asn IN ('53171') THEN 'Omni Telecom'\n            ELSE c.as_name\n        END IN ($isp)\n        AND d.server_site IN ($server)\n    GROUP BY \"Provedor\"\n\n    UNION ALL\n\n    SELECT\n        '📊 TOTAL GERAL' AS \"Provedor\",\n        count() AS \"Total de Testes\",\n        count(DISTINCT d.client_ip) AS \"Clientes Únicos\",\n        round(avg(d.mean_throughput_mbps), 2) AS \"Média (Mbps)\",\n        approx_median(d.mean_throughput_mbps) AS \"Mediana (Mbps)\",\n        round(min(d.mean_throughput_mbps), 2) AS \"Mínimo (Mbps)\",\n        round(max(d.mean_throughput_mbps), 2) AS \"Máximo (Mbps)\"\n    FROM upload d\n    JOIN client c ON d.client_ip = c.client_ip\n    WHERE $__timeFilter(d.test_time)\n        AND d.mean_throughput_mbps >= 0\n        AND CASE\n            WHEN c.asn IN ('18881', '26599', '27699', '19182', '10429') THEN 'Telefônica'\n            WHEN c.asn IN ('28573', '4230', '22085') THEN 'Claro'\n            WHEN c.asn IN ('265303') THEN 'TV Alphaville'\n            WHEN c.asn IN ('14868') THEN 'COPEL Telecom'\n            WHEN c.asn IN ('53184') THEN 'INB Telecom'\n            WHEN c.asn IN ('262907') THEN 'Avato Tecnologia'\n            WHEN c.asn IN ('61844') THEN 'New Master'\n            WHEN c.asn IN ('28258') THEN 'Powerline Internet'\n            WHEN c.asn IN ('273683') THEN 'Desconhecido'\n            WHEN c.asn IN ('22689') THEN 'Sercomtel'\n            WHEN c.asn IN ('53062') THEN 'G G Net'\n            WHEN c.asn IN ('264228') THEN 'Brasil Starlink'\n            WHEN c.asn IN ('28669') THEN 'America Net'\n            WHEN c.asn IN ('263645') THEN 'Fixtell Telecom'\n            WHEN c.asn IN ('266949') THEN 'Divifibra'\n            WHEN c.asn IN ('262700') THEN 'Efibra Telecom'\n            WHEN c.asn IN ('28658') THEN 'Gigalink'\n            WHEN c.asn IN ('262673') THEN 'Lafaiete'\n            WHEN c.asn IN ('52900') THEN 'Quality Telecom'\n            WHEN c.asn IN ('263629') THEN 'Celloni'\n            WHEN c.asn IN ('52940') THEN 'Nemesis'\n            WHEN c.asn IN ('262671') THEN 'S & M Informática'\n            WHEN c.asn IN ('28241') THEN 'Viaceu Internet'\n            WHEN c.asn IN ('53191') THEN 'Plug Telecom'\n            WHEN c.asn IN ('28263') THEN 'Ensite Brasil'\n            WHEN c.asn IN ('263072') THEN 'BD Fibra Telecom'\n            WHEN c.asn IN ('53171') THEN 'Omni Telecom'\n            ELSE c.as_name\n        END IN ($isp)\n        \n) AS resultado\nORDER BY \"Total de Testes\" DESC",
     "selectedFormat": 1
    }
   ]
  },
  {
   "title": "Mediana de Download por Provedor",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "Mbps" } },
   "targets": [
    {
     "rawSql": "SELECT\n    CASE\n        WHEN c.asn IN ('18881', '26599', '27699', '19182', '10429') THEN 'Telefônica'\n        WHEN c.asn IN ('28573', '4230', '22085') THEN 'Claro'\n        WHEN c.asn IN ('265303') THEN 'TV Alphaville'\n        WHEN c.asn IN ('14868') THEN 'COPEL Telecom'\n        WHEN c.asn IN ('53184') THEN 'INB Telecom'\n        WHEN c.asn IN ('262907') THEN 'Avato Tecnologia'\n        WHEN c.asn IN ('61844') THEN 'New Master'\n        WHEN c.asn IN ('28258') THEN 'Powerline Internet'\n        WHEN c.asn IN ('273683') THEN 'Desconhecido'\n        WHEN c.asn IN ('22689') THEN 'Sercomtel'\n        WHEN c.asn IN ('53062') THEN 'G G Net'\n        WHEN c.asn IN ('264228') THEN 'Brasil Starlink'\n        WHEN c.asn IN ('28669') THEN 'America Net'\n        WHEN c.asn IN ('263645') THEN 'Fixtell Telecom'\n        WHEN c.asn IN ('266949') THEN 'Divifibra'\n        WHEN c.asn IN ('262700') THEN 'Efibra Telecom'\n        WHEN c.asn IN ('28658') THEN 'Gigalink'\n        WHEN c.asn IN ('262673') THEN 'Lafaiete'\n        WHEN c.asn IN ('52900') THEN 'Quality Telecom'\n        WHEN c.asn IN ('263629') THEN 'Celloni'\n        WHEN c.asn IN ('52940') THEN 'Nemesis'\n        WHEN c.asn IN ('262671') THEN 'S & M Informática'\n        WHEN c.asn IN ('28241') THEN 'Viaceu Internet'\n        WHEN c.asn IN ('53191') THEN 'Plug Telecom'\n        WHEN c.asn IN ('28263') THEN 'Ensite Brasil'\n        WHEN c.asn IN ('263072') THEN 'BD Fibra Telecom'\n        WHEN c.asn IN ('53171') THEN 'Omni Telecom'\n        ELSE c.as_name\n    END AS provedor,\n    approx_median(d.mean_throughput_mbps) AS mediana_download_mbps\nFROM download d\nJOIN client c ON d.client_ip = c.client_ip\nWHERE $__timeFilter(d.test_time)\n    AND d.mean_throughput_mbps >= 0\n    AND CASE WHEN c.asn IN ('18881', '26599', '27699', '19182', '10429') THEN 'Telefônica' WHEN c.asn IN ('28573', '4230', '22085') THEN 'Claro' WHEN c.asn IN ('265303') THEN 'TV Alphaville' WHEN c.asn IN ('14868') THEN 'COPEL Telecom' WHEN c.asn IN ('53184') THEN 'INB Telecom' WHEN c.asn IN ('262907') THEN 'Avato Tecnologia' WHEN c.asn IN ('61844') THEN 'New Master' WHEN c.asn IN ('28258') THEN 'Powerline Internet' WHEN c.asn IN ('273683') THEN 'Desconhecido' WHEN c.asn IN ('22689') THEN 'Sercomtel' WHEN c.asn IN ('53062') THEN 'G G Net' WHEN c.asn IN ('264228') THEN 'Brasil Starlink' WHEN c.asn IN ('28669') THEN 'America Net' WHEN c.asn IN ('263645') THEN 'Fixtell Telecom' WHEN c.asn IN ('266949') THEN 'Divifibra' WHEN c.asn IN ('262700') THEN 'Efibra Telecom' WHEN c.asn IN ('28658') THEN 'Gigalink' WHEN c.asn IN ('262673') THEN 'Lafaiete' WHEN c.asn IN ('52900') THEN 'Quality Telecom' WHEN c.asn IN ('263629') THEN 'Celloni' WHEN c.asn IN ('52940') THEN 'Nemesis' WHEN c.asn IN ('262671') THEN 'S & M Informática' WHEN c.asn IN ('28241') THEN 'Viaceu Internet' WHEN c.asn IN ('53191') THEN 'Plug Telecom' WHEN c.asn IN ('28263') THEN 'Ensite Brasil' WHEN c.asn IN ('263072') THEN 'BD Fibra Telecom' WHEN c.asn IN ('53171') THEN 'Omni Telecom' ELSE c.as_name END IN ($isp)\n    AND d.server_site IN ($server)\nGROUP BY provedor\nORDER BY mediana_download_mbps DESC",
     "selectedFormat": 2
    }
   ]
  },
  {
   "title": "Mediana de Upload por Provedor",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "Mbps" } },
   "targets": [
    {
     "rawSql": "SELECT\n    CASE\n        WHEN c.asn IN ('18881', '26599', '27699', '19182', '10429') THEN 'Telefônica'\n        WHEN c.asn IN ('28573', '4230', '22085') THEN 'Claro'\n        WHEN c.asn IN ('265303') THEN 'TV Alphaville'\n        WHEN c.asn IN ('14868') THEN 'COPEL Telecom'\n        WHEN c.asn IN ('53184') THEN 'INB Telecom'\n        WHEN c.asn IN ('262907') THEN 'Avato Tecnologia'\n        WHEN c.asn IN ('61844') THEN 'New Master'\n        WHEN c.asn IN ('28258') THEN 'Powerline Internet'\n        WHEN c.asn IN ('273683') THEN 'Desconhecido'\n        WHEN c.asn IN ('22689') THEN 'Sercomtel'\n        WHEN c.asn IN ('53062') THEN 'G G Net'\n        WHEN c.asn IN ('264228') THEN 'Brasil Starlink'\n        WHEN c.asn IN ('28669') THEN 'America Net'\n        WHEN c.asn IN ('263645') THEN 'Fixtell Telecom'\n        WHEN c.asn IN ('266949') THEN 'Divifibra'\n        WHEN c.asn IN ('262700') THEN 'Efibra Telecom'\n        WHEN c.asn IN ('28658') THEN 'Gigalink'\n        WHEN c.asn IN ('262673') THEN 'Lafaiete'\n        WHEN c.asn IN ('52900') THEN 'Quality Telecom'\n        WHEN c.asn IN ('263629') THEN 'Celloni'\n        WHEN c.asn IN ('52940') THEN 'Nemesis'\n        WHEN c.asn IN ('262671') THEN 'S & M Informática'\n        WHEN c.asn IN ('28241') THEN 'Viaceu Internet'\n        WHEN c.asn IN ('53191') THEN 'Plug Telecom'\n        WHEN c.asn IN ('28263') THEN 'Ensite Brasil'\n        WHEN c.asn IN ('263072') THEN 'BD Fibra Telecom'\n        WHEN c.asn IN ('53171') THEN 'Omni Telecom'\n        ELSE c.as_name\n    END AS provedor,\n    approx_median(d.mean_throughput_mbps) AS mediana_upload_mbps\nFROM upload d\nJOIN client c ON d.client_ip = c.client_ip\nWHERE $__timeFilter(d.test_time)\n    AND d.mean_throughput_mbps >= 0\n    AND CASE WHEN c.asn IN ('18881', '26599', '27699', '19182', '10429') THEN 'Telefônica' WHEN c.asn IN ('28573', '4230', '22085') THEN 'Claro' WHEN c.asn IN ('265303') THEN 'TV Alphaville' WHEN c.asn IN ('14868') THEN 'COPEL Telecom' WHEN c.asn IN ('53184') THEN 'INB Telecom' WHEN c.asn IN ('262907') THEN 'Avato Tecnologia' WHEN c.asn IN ('61844') THEN 'New Master' WHEN c.asn IN ('28258') THEN 'Powerline Internet' WHEN c.asn IN ('273683') THEN 'Desconhecido' WHEN c.asn IN ('22689') THEN 'Sercomtel' WHEN c.asn IN ('53062') THEN 'G G Net' WHEN c.asn IN ('264228') THEN 'Brasil Starlink' WHEN c.asn IN ('28669') THEN 'America Net' WHEN c.asn IN ('263645') THEN 'Fixtell Telecom' WHEN c.asn IN ('266949') THEN 'Divifibra' WHEN c.asn IN ('262700') THEN 'Efibra Telecom' WHEN c.asn IN ('28658') THEN 'Gigalink' WHEN c.asn IN ('262673') THEN 'Lafaiete' WHEN c.asn IN ('52900') THEN 'Quality Telecom' WHEN c.asn IN ('263629') THEN 'Celloni' WHEN c.asn IN ('52940') THEN 'Nemesis' WHEN c.asn IN ('262671') THEN 'S & M Informática' WHEN c.asn IN ('28241') THEN 'Viaceu Internet' WHEN c.asn IN ('53191') THEN 'Plug Telecom' WHEN c.asn IN ('28263') THEN 'Ensite Brasil' WHEN c.asn IN ('263072') THEN 'BD Fibra Telecom' WHEN c.asn IN ('53171') THEN 'Omni Telecom' ELSE c.as_name END IN ($isp)\n    AND d.server_site IN ($server)\nGROUP BY provedor\nORDER BY mediana_upload_mbps DESC",
     "selectedFormat": 2
    }
   ]
  },
  {
   "title": "RTT Médio por Provedor",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "rawSql": "SELECT\n    CASE\n        WHEN c.asn IN ('18881', '26599', '27699', '19182', '10429') THEN 'Telefônica'\n        WHEN c.asn IN ('28573', '4230', '22085') THEN 'Claro'\n        WHEN c.asn IN ('265303') THEN 'TV Alphaville'\n        WHEN c.asn IN ('14868') THEN 'COPEL Telecom'\n        WHEN c.asn IN ('53184') THEN 'INB Telecom'\n        WHEN c.asn IN ('262907') THEN 'Avato Tecnologia'\n        WHEN c.asn IN ('61844') THEN 'New Master'\n        WHEN c.asn IN ('28258') THEN 'Powerline Internet'\n        WHEN c.asn IN ('273683') THEN 'Desconhecido'\n        WHEN c.asn IN ('22689') THEN 'Sercomtel'\n        WHEN c.asn IN ('53062') THEN 'G G Net'\n        WHEN c.asn IN ('264228') THEN 'Brasil Starlink'\n        WHEN c.asn IN ('28669') THEN 'America Net'\n        WHEN c.asn IN ('263645') THEN 'Fixtell Telecom'\n        WHEN c.asn IN ('266949') THEN 'Divifibra'\n        WHEN c.asn IN ('262700') THEN 'Efibra Telecom'\n        WHEN c.asn IN ('28658') THEN 'Gigalink'\n        WHEN c.asn IN ('262673') THEN 'Lafaiete'\n        WHEN c.asn IN ('52900') THEN 'Quality Telecom'\n        WHEN c.asn IN ('263629') THEN 'Celloni'\n        WHEN c.asn IN ('52940') THEN 'Nemesis'\n        WHEN c.asn IN ('262671') THEN 'S & M Informática'\n        WHEN c.asn IN ('28241') THEN 'Viaceu Internet'\n        WHEN c.asn IN ('53191') THEN 'Plug Telecom'\n        WHEN c.asn IN ('28263') THEN 'Ensite Brasil'\n        WHEN c.asn IN ('263072') THEN 'BD Fibra Telecom'\n        WHEN c.asn IN ('53171') THEN 'Omni Telecom'\n        ELSE c.as_name\n    END AS provedor,\n    round(avg(d.min_rtt), 2) AS rtt_medio_ms\nFROM download d\nJOIN client c ON d.client_ip = c.client_ip\nWHERE $__timeFilter(d.test_time)\n    AND d.min_rtt >= 0\n    AND d.min_rtt <= 1500000\n    AND CASE WHEN c.asn IN ('18881', '26599', '27699', '19182', '10429') THEN 'Telefônica' WHEN c.asn IN ('28573', '4230', '22085') THEN 'Claro' WHEN c.asn IN ('265303') THEN 'TV Alphaville' WHEN c.asn IN ('14868') THEN 'COPEL Telecom' WHEN c.asn IN ('53184') THEN 'INB Telecom' WHEN c.asn IN ('262907') THEN 'Avato Tecnologia' WHEN c.asn IN ('61844') THEN 'New Master' WHEN c.asn IN ('28258') THEN 'Powerline Internet' WHEN c.asn IN ('273683') THEN 'Desconhecido' WHEN c.asn IN ('22689') THEN 'Sercomtel' WHEN c.asn IN ('53062') THEN 'G G Net' WHEN c.asn IN ('264228') THEN 'Brasil Starlink' WHEN c.asn IN ('28669') THEN 'America Net' WHEN c.asn IN ('263645') THEN 'Fixtell Telecom' WHEN c.asn IN ('266949') THEN 'Divifibra' WHEN c.asn IN ('262700') THEN 'Efibra Telecom' WHEN c.asn IN ('28658') THEN 'Gigalink' WHEN c.asn IN ('262673') THEN 'Lafaiete' WHEN c.asn IN ('52900') THEN 'Quality Telecom' WHEN c.asn IN ('263629') THEN 'Celloni' WHEN c.asn IN ('52940') THEN 'Nemesis' WHEN c.asn IN ('262671') THEN 'S & M Informática' WHEN c.asn IN ('28241') THEN 'Viaceu Internet' WHEN c.asn IN ('53191') THEN 'Plug Telecom' WHEN c.asn IN ('28263') THEN 'Ensite Brasil' WHEN c.asn IN ('263072') THEN 'BD Fibra Telecom' WHEN c.asn IN ('53171') THEN 'Omni Telecom' ELSE c.as_name END IN ($isp)\n    AND d.server_site IN ($server)\nGROUP BY provedor\nORDER BY rtt_medio_ms ASC",
     "selectedFormat": 2
    }
   ]
  },
  {
   "title": "Loss Rate Médio por Provedor",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "rawSql": "SELECT\n    CASE\n        WHEN c.asn IN ('18881', '26599', '27699', '19182', '10429') THEN 'Telefônica'\n        WHEN c.asn IN ('28573', '4230', '22085') THEN 'Claro'\n        WHEN c.asn IN ('265303') THEN 'TV Alphaville'\n        WHEN c.asn IN ('14868') THEN 'COPEL Telecom'\n        WHEN c.asn IN ('53184') THEN 'INB Telecom'\n        WHEN c.asn IN ('262907') THEN 'Avato Tecnologia'\n        WHEN c.asn IN ('61844') THEN 'New Master'\n        WHEN c.asn IN ('28258') THEN 'Powerline Internet'\n        WHEN c.asn IN ('273683') THEN 'Desconhecido'\n        WHEN c.asn IN ('22689') THEN 'Sercomtel'\n        WHEN c.asn IN ('53062') THEN 'G G Net'\n        WHEN c.asn IN ('264228') THEN 'Brasil Starlink'\n        WHEN c.asn IN ('28669') THEN 'America Net'\n        WHEN c.asn IN ('263645') THEN 'Fixtell Telecom'\n        WHEN c.asn IN ('266949') THEN 'Divifibra'\n        WHEN c.asn IN ('262700') THEN 'Efibra Telecom'\n        WHEN c.asn IN ('28658') THEN 'Gigalink'\n        WHEN c.asn IN ('262673') THEN 'Lafaiete'\n        WHEN c.asn IN ('52900') THEN 'Quality Telecom'\n        WHEN c.asn IN ('263629') THEN 'Celloni'\n        WHEN c.asn IN ('52940') THEN 'Nemesis'\n        WHEN c.asn IN ('262671') THEN 'S & M Informática'\n        WHEN c.asn IN ('28241') THEN 'Viaceu Internet'\n        WHEN c.asn IN ('53191') THEN 'Plug Telecom'\n        WHEN c.asn IN ('28263') THEN 'Ensite Brasil'\n        WHEN c.asn IN ('263072') THEN 'BD Fibra Telecom'\n        WHEN c.asn IN ('53171') THEN 'Omni Telecom'\n        ELSE c.as_name\n    END AS provedor,\n    round(avg(d.loss_rate), 4) AS loss_rate_medio\nFROM download d\nJOIN client c ON d.client_ip = c.client_ip\nWHERE $__timeFilter(d.test_time)\n    AND d.loss_rate >= 0\n    AND CASE WHEN c.asn IN ('18881', '26599', '27699', '19182', '10429') THEN 'Telefônica' WHEN c.asn IN ('28573', '4230', '22085') THEN 'Claro' WHEN c.asn IN ('265303') THEN 'TV Alphaville' WHEN c.asn IN ('14868') THEN 'COPEL Telecom' WHEN c.asn IN ('53184') THEN 'INB Telecom' WHEN c.asn IN ('262907') THEN 'Avato Tecnologia' WHEN c.asn IN ('61844') THEN 'New Master' WHEN c.asn IN ('28258') THEN 'Powerline Internet' WHEN c.asn IN ('273683') THEN 'Desconhecido' WHEN c.asn IN ('22689') THEN 'Sercomtel' WHEN c.asn IN ('53062') THEN 'G G Net' WHEN c.asn IN ('264228') THEN 'Brasil Starlink' WHEN c.asn IN ('28669') THEN 'America Net' WHEN c.asn IN ('263645') THEN 'Fixtell Telecom' WHEN c.asn IN ('266949') THEN 'Divifibra' WHEN c.asn IN ('262700') THEN 'Efibra Telecom' WHEN c.asn IN ('28658') THEN 'Gigalink' WHEN c.asn IN ('262673') THEN 'Lafaiete' WHEN c.asn IN ('52900') THEN 'Quality Telecom' WHEN c.asn IN ('263629') THEN 'Celloni' WHEN c.asn IN ('52940') THEN 'Nemesis' WHEN c.asn IN ('262671') THEN 'S & M Informática' WHEN c.asn IN ('28241') THEN 'Viaceu Internet' WHEN c.asn IN ('53191') THEN 'Plug Telecom' WHEN c.asn IN ('28263') THEN 'Ensite Brasil' WHEN c.asn IN ('263072') THEN 'BD Fibra Telecom' WHEN c.asn IN ('53171') THEN 'Omni Telecom' ELSE c.as_name END IN ($isp)\n    AND d.server_site IN ($server)\nGROUP BY provedor\nORDER BY loss_rate_medio ASC",
     "selectedFormat": 2
    }
   ]
  },
  {
   "title": "Total de Testes por Provedor",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT\n    CASE\n        WHEN c.asn IN ('18881', '26599', '27699', '19182', '10429') THEN 'Telefônica'\n        WHEN c.asn IN ('28573', '4230', '22085') THEN 'Claro'\n        WHEN c.asn IN ('265303') THEN 'TV Alphaville'\n        WHEN c.asn IN ('14868') THEN 'COPEL Telecom'\n        WHEN c.asn IN ('53184') THEN 'INB Telecom'\n        WHEN c.asn IN ('262907') THEN 'Avato Tecnologia'\n        WHEN c.asn IN ('61844') THEN 'New Master'\n        WHEN c.asn IN ('28258') THEN 'Powerline Internet'\n        WHEN c.asn IN ('273683') THEN 'Desconhecido'\n        WHEN c.asn IN ('22689') THEN 'Sercomtel'\n        WHEN c.asn IN ('53062') THEN 'G G Net'\n        WHEN c.asn IN ('264228') THEN 'Brasil Starlink'\n        WHEN c.asn IN ('28669') THEN 'America Net'\n        WHEN c.asn IN ('263645') THEN 'Fixtell Telecom'\n        WHEN c.asn IN ('266949') THEN 'Divifibra'\n        WHEN c.asn IN ('262700') THEN 'Efibra Telecom'\n        WHEN c.asn IN ('28658') THEN 'Gigalink'\n        WHEN c.asn IN ('262673') THEN 'Lafaiete'\n        WHEN c.asn IN ('52900') THEN 'Quality Telecom'\n        WHEN c.asn IN ('263629') THEN 'Celloni'\n        WHEN c.asn IN ('52940') THEN 'Nemesis'\n        WHEN c.asn IN ('262671') THEN 'S & M Informática'\n        WHEN c.asn IN ('28241') THEN 'Viaceu Internet'\n        WHEN c.asn IN ('53191') THEN 'Plug Telecom'\n        WHEN c.asn IN ('28263') THEN 'Ensite Brasil'\n        WHEN c.asn IN ('263072') THEN 'BD Fibra Telecom'\n        WHEN c.asn IN ('53171') THEN 'Omni Telecom'\n        ELSE c.as_name\n    END AS provedor,\n    count() AS total_testes\nFROM download d\nJOIN client c ON d.client_ip = c.client_ip\nWHERE $__timeFilter(d.test_time)\n    AND CASE WHEN c.asn IN ('18881', '26599', '27699', '19182', '10429') THEN 'Telefônica' WHEN c.asn IN ('28573', '4230', '22085') THEN 'Claro' WHEN c.asn IN ('265303') THEN 'TV Alphaville' WHEN c.asn IN ('14868') THEN 'COPEL Telecom' WHEN c.asn IN ('53184') THEN 'INB Telecom' WHEN c.asn IN ('262907') THEN 'Avato Tecnologia' WHEN c.asn IN ('61844') THEN 'New Master' WHEN c.asn IN ('28258') THEN 'Powerline Internet' WHEN c.asn IN ('273683') THEN 'Desconhecido' WHEN c.asn IN ('22689') THEN 'Sercomtel' WHEN c.asn IN ('53062') THEN 'G G Net' WHEN c.asn IN ('264228') THEN 'Brasil Starlink' WHEN c.asn IN ('28669') THEN 'America Net' WHEN c.asn IN ('263645') THEN 'Fixtell Telecom' WHEN c.asn IN ('266949') THEN 'Divifibra' WHEN c.asn IN ('262700') THEN 'Efibra Telecom' WHEN c.asn IN ('28658') THEN 'Gigalink' WHEN c.asn IN ('262673') THEN 'Lafaiete' WHEN c.asn IN ('52900') THEN 'Quality Telecom' WHEN c.asn IN ('263629') THEN 'Celloni' WHEN c.asn IN ('52940') THEN 'Nemesis' WHEN c.asn IN ('262671') THEN 'S & M Informática' WHEN c.asn IN ('28241') THEN 'Viaceu Internet' WHEN c.asn IN ('53191') THEN 'Plug Telecom' WHEN c.asn IN ('28263') THEN 'Ensite Brasil' WHEN c.asn IN ('263072') THEN 'BD Fibra Telecom' WHEN c.asn IN ('53171') THEN 'Omni Telecom' ELSE c.as_name END IN ($isp)\n    AND d.server_site IN ($server)\nGROUP BY provedor\nORDER BY total_testes DESC",
     "selectedFormat": 2
    }
   ]
  }
 ]
}