{
 "title": "NDT Dashboard — Parte 3b: Bar Charts",
 "tags": [
  "ndt",
  "questdb"
 ],
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "isp",
    "label": "ISP",
    "query": "SELECT DISTINCT CASE WHEN asn IN ('18881', '26599', '27699', '19182', '10429') THEN 'Telefônica' WHEN asn IN ('28573', '4230', '22085') THEN 'Claro' WHEN asn IN ('265303') THEN 'TV Alphaville' WHEN asn IN ('14868') THEN 'COPEL Telecom' WHEN asn IN ('53184') THEN 'INB Telecom' WHEN asn IN ('262907') THEN 'Avato Tecnologia' WHEN asn IN ('61844') THEN 'New Master' WHEN asn IN ('28258') THEN 'Powerline Internet' WHEN asn IN ('273683') THEN 'Desconhecido' WHEN asn IN ('22689') THEN 'Sercomtel' WHEN asn IN ('53062') THEN 'G G Net' WHEN asn IN ('264228') THEN 'Brasil Starlink' WHEN asn IN ('28669') THEN 'America Net' WHEN asn IN ('263645') THEN 'Fixtell Telecom' WHEN asn IN ('266949') THEN 'Divifibra' WHEN asn IN ('262700') THEN 'Efibra Telecom' WHEN asn IN ('28658') THEN 'Gigalink' WHEN asn IN ('262673') THEN 'Lafaiete' WHEN asn IN ('52900') THEN 'Quality Telecom' WHEN asn IN ('263629') THEN 'Celloni' WHEN asn IN ('52940') THEN 'Nemesis' WHEN asn IN ('262671') THEN 'S & M Informática' WHEN asn IN ('28241') THEN 'Viaceu Internet' WHEN asn IN ('53191') THEN 'Plug Telecom' WHEN asn IN ('28263') THEN 'Ensite Brasil' WHEN asn IN ('263072') THEN 'BD Fibra Telecom' WHEN asn IN ('53171') THEN 'Omni Telecom' ELSE as_name END AS __text, CASE WHEN asn IN ('18881', '26599', '27699', '19182', '10429') THEN 'Telefônica' WHEN asn IN ('28573', '4230', '22085') THEN 'Claro' WHEN asn IN ('265303') THEN 'TV Alphaville' WHEN asn IN ('14868') THEN 'COPEL Telecom' WHEN asn IN ('53184') THEN 'INB Telecom' WHEN asn IN ('262907') THEN 'Avato Tecnologia' WHEN asn IN ('61844') THEN 'New Master' WHEN asn IN ('28258') THEN 'Powerline Internet' WHEN asn IN ('273683') THEN 'Desconhecido' WHEN asn IN ('22689') THEN 'Sercomtel' WHEN asn IN ('53062') THEN 'G G Net' WHEN asn IN ('264228') THEN 'Brasil Starlink' WHEN asn IN ('28669') THEN 'America Net' WHEN asn IN ('263645') THEN 'Fixtell Telecom' WHEN asn IN ('266949') THEN 'Divifibra' WHEN asn IN ('262700') THEN 'Efibra Telecom' WHEN asn IN ('28658') THEN 'Gigalink' WHEN asn IN ('262673') THEN 'Lafaiete' WHEN asn IN ('52900') THEN 'Quality Telecom' WHEN asn IN ('263629') THEN 'Celloni' WHEN asn IN ('52940') THEN 'Nemesis' WHEN asn IN ('262671') THEN 'S & M Informática' WHEN asn IN ('28241') THEN 'Viaceu Internet' WHEN asn IN ('53191') THEN 'Plug Telecom' WHEN asn IN ('28263') THEN 'Ensite Brasil' WHEN asn IN ('263072') THEN 'BD Fibra Telecom' WHEN asn IN ('53171') THEN 'Omni Telecom' ELSE as_name END AS __value FROM client ORDER BY 1"
   },
   {
    "name": "server",
    "label": "Servidor",
    "query": "SELECT DISTINCT server_site FROM download WHERE server_site IS NOT NULL ORDER BY server_site"
   }
  ]
 },
 "panels": [
  {
   "title": "Mediana de Download por Provedor",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Mbps" } },
   "targets": [
    {
     "rawSql": "SELECT\n    CASE\n        WHEN c.asn IN ('18881', '26599', '27699', '19182', '10429') THEN 'Telefônica'\n        WHEN c.asn IN ('28573', '4230', '22085') THEN 'Claro'\n        WHEN c.asn IN ('265303') THEN 'TV Alphaville'\n        WHEN c.asn IN ('14868') THEN 'COPEL Telecom'\n        WHEN c.asn IN ('53184') THEN 'INB Telecom'\n        WHEN c.asn IN ('262907') THEN 'Avato Tecnologia'\n        WHEN c.asn IN ('61844') THEN 'New Master'\n        WHEN c.asn IN ('28258') THEN 'Powerline Internet'\n        WHEN c.asn IN ('273683') THEN 'Desconhecido'\n        WHEN c.asn IN ('22689') THEN 'Sercomtel'\n        WHEN c.asn IN ('53062') THEN 'G G Net'\n        WHEN c.asn IN ('264228') THEN 'Brasil Starlink'\n        WHEN c.asn IN ('28669') THEN 'America Net'\n        WHEN c.asn IN ('263645') THEN 'Fixtell Telecom'\n        WHEN c.asn IN ('266949') THEN 'Divifibra'\n        WHEN c.asn IN ('262700') THEN 'Efibra Telecom'\n        WHEN c.asn IN ('28658') THEN 'Gigalink'\n        WHEN c.asn IN ('262673') THEN 'Lafaiete'\n        WHEN c.asn IN ('52900') THEN 'Quality Telecom'\n        WHEN c.asn IN ('263629') THEN 'Celloni'\n        WHEN c.asn IN ('52940') THEN 'Nemesis'\n        WHEN c.asn IN ('262671') THEN 'S & M Informática'\n        WHEN c.asn IN ('28241') THEN 'Viaceu Internet'\n        WHEN c.asn IN ('53191') THEN 'Plug Telecom'\n        WHEN c.asn IN ('28263') THEN 'Ensite Brasil'\n        WHEN c.asn IN ('263072') THEN 'BD Fibra Telecom'\n        WHEN c.asn IN ('53171') THEN 'Omni Telecom'\n        ELSE c.as_name\n    END AS provedor,\n    approx_median(d.mean_throughput_mbps) AS mediana_download_mbps\nFROM download d\nJOIN client c ON d.client_ip = c.client_ip\nWHERE $__timeFilter(d.test_time)\n    AND d.mean_throughput_mbps >= 0\n    AND CASE WHEN c.asn IN ('18881', '26599', '27699', '19182', '10429') THEN 'Telefônica' WHEN c.asn IN ('28573', '4230', '22085') THEN 'Claro' WHEN c.asn IN ('265303') THEN 'TV Alphaville' WHEN c.asn IN ('14868') THEN 'COPEL Telecom' WHEN c.asn IN ('53184') THEN 'INB Telecom' WHEN c.asn IN ('262907') THEN 'Avato Tecnologia' WHEN c.asn IN ('61844') THEN 'New Master' WHEN c.asn IN ('28258') THEN 'Powerline Internet' WHEN c.asn IN ('273683') THEN 'Desconhecido' WHEN c.asn IN ('22689') THEN 'Sercomtel' WHEN c.asn IN ('53062') THEN 'G G Net' WHEN c.asn IN ('264228') THEN 'Brasil Starlink' WHEN c.asn IN ('28669') THEN 'America Net' WHEN c.asn IN ('263645') THEN 'Fixtell Telecom' WHEN c.asn IN ('266949') THEN 'Divifibra' WHEN c.asn IN ('262700') THEN 'Efibra Telecom' WHEN c.asn IN ('28658') THEN 'Gigalink' WHEN c.asn IN ('262673') THEN 'Lafaiete' WHEN c.asn IN ('52900') THEN 'Quality Telecom' WHEN c.asn IN ('263629') THEN 'Celloni' WHEN c.asn IN ('52940') THEN 'Nemesis' WHEN c.asn IN ('262671') THEN 'S & M Informática' WHEN c.asn IN ('28241') THEN 'Viaceu Internet' WHEN c.asn IN ('53191') THEN 'Plug Telecom' WHEN c.asn IN ('28263') THEN 'Ensite Brasil' WHEN c.asn IN ('263072') THEN 'BD Fibra Telecom' WHEN c.asn IN ('53171') THEN 'Omni Telecom' ELSE c.as_name END IN ($isp)\n    AND d.server_site IN ($server)\nGROUP BY provedor\nORDER BY mediana_download_mbps DESC",
     "selectedFormat": 2
    }
   ]
  },
  {
   "title": "Mediana de Upload por Provedor",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "Mbps" } },
   "targets": [
    {
     "rawSql": "SELECT\n    CASE\n        WHEN c.asn IN ('18881', '26599', '27699', '19182', '10429') THEN 'Telefônica'\n        WHEN c.asn IN ('28573', '4230', '22085') THEN 'Claro'\n        WHEN c.asn IN ('265303') THEN 'TV Alphaville'\n        WHEN c.asn IN ('14868') THEN 'COPEL Telecom'\n        WHEN c.asn IN ('53184') THEN 'INB Telecom'\n        WHEN c.asn IN ('262907') THEN 'Avato Tecnologia'\n        WHEN c.asn IN ('61844') THEN 'New Master'\n        WHEN c.asn IN ('28258') THEN 'Powerline Internet'\n        WHEN c.asn IN ('273683') THEN 'Desconhecido'\n        WHEN c.asn IN ('22689') THEN 'Sercomtel'\n        WHEN c.asn IN ('53062') THEN 'G G Net'\n        WHEN c.asn IN ('264228') THEN 'Brasil Starlink'\n        WHEN c.asn IN ('28669') THEN 'America Net'\n        WHEN c.asn IN ('263645') THEN 'Fixtell Telecom'\n        WHEN c.asn IN ('266949') THEN 'Divifibra'\n        WHEN c.asn IN ('262700') THEN 'Efibra Telecom'\n        WHEN c.asn IN ('28658') THEN 'Gigalink'\n        WHEN c.asn IN ('262673') THEN 'Lafaiete'\n        WHEN c.asn IN ('52900') THEN 'Quality Telecom'\n        WHEN c.asn IN ('263629') THEN 'Celloni'\n        WHEN c.asn IN ('52940') THEN 'Nemesis'\n        WHEN c.asn IN ('262671') THEN 'S & M Informática'\n        WHEN c.asn IN ('28241') THEN 'Viaceu Internet'\n        WHEN c.asn IN ('53191') THEN 'Plug Telecom'\n        WHEN c.asn IN ('28263') THEN 'Ensite Brasil'\n        WHEN c.asn IN ('263072') THEN 'BD Fibra Telecom'\n        WHEN c.asn IN ('53171') THEN 'Omni Telecom'\n        ELSE c.as_name\n    END AS provedor,\n    approx_median(d.mean_throughput_mbps) AS mediana_upload_mbps\nFROM upload d\nJOIN client c ON d.client_ip = c.client_ip\nWHERE $__timeFilter(d.test_time)\n    AND d.mean_throughput_mbps >= 0\n    AND CASE WHEN c.asn IN ('18881', '26599', '27699', '19182', '10429') THEN 'Telefônica' WHEN c.asn IN ('28573', '4230', '22085') THEN 'Claro' WHEN c.asn IN ('265303') THEN 'TV Alphaville' WHEN c.asn IN ('14868') THEN 'COPEL Telecom' WHEN c.asn IN ('53184') THEN 'INB Telecom' WHEN c.asn IN ('262907') THEN 'Avato Tecnologia' WHEN c.asn IN ('61844') THEN 'New Master' WHEN c.asn IN ('28258') THEN 'Powerline Internet' WHEN c.asn IN ('273683') THEN 'Desconhecido' WHEN c.asn IN ('22689') THEN 'Sercomtel' WHEN c.asn IN ('53062') THEN 'G G Net' WHEN c.asn IN ('264228') THEN 'Brasil Starlink' WHEN c.asn IN ('28669') THEN 'America Net' WHEN c.asn IN ('263645') THEN 'Fixtell Telecom' WHEN c.asn IN ('266949') THEN 'Divifibra' WHEN c.asn IN ('262700') THEN 'Efibra Telecom' WHEN c.asn IN ('28658') THEN 'Gigalink' WHEN c.asn IN ('262673') THEN 'Lafaiete' WHEN c.asn IN ('52900') THEN 'Quality Telecom' WHEN c.asn IN ('263629') THEN 'Celloni' WHEN c.asn IN ('52940') THEN 'Nemesis' WHEN c.asn IN ('262671') THEN 'S & M Informática' WHEN c.asn IN ('28241') THEN 'Viaceu Internet' WHEN c.asn IN ('53191') THEN 'Plug Telecom' WHEN c.asn IN ('28263') THEN 'Ensite Brasil' WHEN c.asn IN ('263072') THEN 'BD Fibra Telecom' WHEN c.asn IN ('53171') THEN 'Omni Telecom' ELSE c.as_name END IN ($isp)\n    AND d.server_site IN ($server)\nGROUP BY provedor\nORDER BY mediana_upload_mbps DESC",
     "selectedFormat": 2
    }
   ]
  },
  {
   "title": "RTT Médio por Provedor",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "rawSql": "SELECT\n    CASE\n        WHEN c.asn IN ('18881', '26599', '27699', '19182', '10429') THEN 'Telefônica'\n        WHEN c.asn IN ('28573', '4230', '22085') THEN 'Claro'\n        WHEN c.asn IN ('265303') THEN 'TV Alphaville'\n        WHEN c.asn IN ('14868') THEN 'COPEL Telecom'\n        WHEN c.asn IN ('53184') THEN 'INB Telecom'\n        WHEN c.asn IN ('262907') THEN 'Avato Tecnologia'\n        WHEN c.asn IN ('61844') THEN 'New Master'\n        WHEN c.asn IN ('28258') THEN 'Powerline Internet'\n        WHEN c.asn IN ('273683') THEN 'Desconhecido'\n        WHEN c.asn IN ('22689') THEN 'Sercomtel'\n        WHEN c.asn IN ('53062') THEN 'G G Net'\n        WHEN c.asn IN ('264228') THEN 'Brasil Starlink'\n        WHEN c.asn IN ('28669') THEN 'America Net'\n        WHEN c.asn IN ('263645') THEN 'Fixtell Telecom'\n        WHEN c.asn IN ('266949') THEN 'Divifibra'\n        WHEN c.asn IN ('262700') THEN 'Efibra Telecom'\n        WHEN c.asn IN ('28658') THEN 'Gigalink'\n        WHEN c.asn IN ('262673') THEN 'Lafaiete'\n        WHEN c.asn IN ('52900') THEN 'Quality Telecom'\n        WHEN c.asn IN ('263629') THEN 'Celloni'\n        WHEN c.asn IN ('52940') THEN 'Nemesis'\n        WHEN c.asn IN ('262671') THEN 'S & M Informática'\n        WHEN c.asn IN ('28241') THEN 'Viaceu Internet'\n        WHEN c.asn IN ('53191') THEN 'Plug Telecom'\n        WHEN c.asn IN ('28263') THEN 'Ensite Brasil'\n        WHEN c.asn IN ('263072') THEN 'BD Fibra Telecom'\n        WHEN c.asn IN ('53171') THEN 'Omni Telecom'\n        ELSE c.as_name\n    END AS provedor,\n    round(avg(d.min_rtt), 2) AS rtt_medio_ms\nFROM download d\nJOIN client c ON d.client_ip = c.client_ip\nWHERE $__timeFilter(d.test_time)\n    AND d.min_rtt >= 0\n    AND d.min_rtt <= 1500000\n    AND CASE WHEN c.asn IN ('18881', '26599', '27699', '19182', '10429') THEN 'Telefônica' WHEN c.asn IN ('28573', '4230', '22085') THEN 'Claro' WHEN c.asn IN ('265303') THEN 'TV Alphaville' WHEN c.asn IN ('14868') THEN 'COPEL Telecom' WHEN c.asn IN ('53184') THEN 'INB Telecom' WHEN c.asn IN ('262907') THEN 'Avato Tecnologia' WHEN c.asn IN ('61844') THEN 'New Master' WHEN c.asn IN ('28258') THEN 'Powerline Internet' WHEN c.asn IN ('273683') THEN 'Desconhecido' WHEN c.asn IN ('22689') THEN 'Sercomtel' WHEN c.asn IN ('53062') THEN 'G G Net' WHEN c.asn IN ('264228') THEN 'Brasil Starlink' WHEN c.asn IN ('28669') THEN 'America Net' WHEN c.asn IN ('263645') THEN 'Fixtell Telecom' WHEN c.asn IN ('266949') THEN 'Divifibra' WHEN c.asn IN ('262700') THEN 'Efibra Telecom' WHEN c.asn IN ('28658') THEN 'Gigalink' WHEN c.asn IN ('262673') THEN 'Lafaiete' WHEN c.asn IN ('52900') THEN 'Quality Telecom' WHEN c.asn IN ('263629') THEN 'Celloni' WHEN c.asn IN ('52940') THEN 'Nemesis' WHEN c.asn IN ('262671') THEN 'S & M Informática' WHEN c.asn IN ('28241') THEN 'Viaceu Internet' WHEN c.asn IN ('53191') THEN 'Plug Telecom' WHEN c.asn IN ('28263') THEN 'Ensite Brasil' WHEN c.asn IN ('263072') THEN 'BD Fibra Telecom' WHEN c.asn IN ('53171') THEN 'Omni Telecom' ELSE c.as_name END IN ($isp)\n    AND d.server_site IN ($server)\nGROUP BY provedor\nORDER BY rtt_medio_ms ASC",
     "selectedFormat": 2
    }
   ]
  },
  {
   "title": "Loss Rate Médio por Provedor",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "rawSql": "SELECT\n    CASE\n        WHEN c.asn IN ('18881', '26599', '27699', '19182', '10429') THEN 'Telefônica'\n        WHEN c.asn IN ('28573', '4230', '22085') THEN 'Claro'\n        WHEN c.asn IN ('265303') THEN 'TV Alphaville'\n        WHEN c.asn IN ('14868') THEN 'COPEL Telecom'\n        WHEN c.asn IN ('53184') THEN 'INB Telecom'\n        WHEN c.asn IN ('262907') THEN 'Avato Tecnologia'\n        WHEN c.asn IN ('61844') THEN 'New Master'\n        WHEN c.asn IN ('28258') THEN 'Powerline Internet'\n        WHEN c.asn IN ('273683') THEN 'Desconhecido'\n        WHEN c.asn IN ('22689') THEN 'Sercomtel'\n        WHEN c.asn IN ('53062') THEN 'G G Net'\n        WHEN c.asn IN ('264228') THEN 'Brasil Starlink'\n        WHEN c.asn IN ('28669') THEN 'America Net'\n        WHEN c.asn IN ('263645') THEN 'Fixtell Telecom'\n        WHEN c.asn IN ('266949') THEN 'Divifibra'\n        WHEN c.asn IN ('262700') THEN 'Efibra Telecom'\n        WHEN c.asn IN ('28658') THEN 'Gigalink'\n        WHEN c.asn IN ('262673') THEN 'Lafaiete'\n        WHEN c.asn IN ('52900') THEN 'Quality Telecom'\n        WHEN c.asn IN ('263629') THEN 'Celloni'\n        WHEN c.asn IN ('52940') THEN 'Nemesis'\n        WHEN c.asn IN ('262671') THEN 'S & M Informática'\n        WHEN c.asn IN ('28241') THEN 'Viaceu Internet'\n        WHEN c.asn IN ('53191') THEN 'Plug Telecom'\n        WHEN c.asn IN ('28263') THEN 'Ensite Brasil'\n        WHEN c.asn IN ('263072') THEN 'BD Fibra Telecom'\n        WHEN c.asn IN ('53171') THEN 'Omni Telecom'\n        ELSE c.as_name\n    END AS provedor,\n    round(avg(d.loss_rate), 4) AS loss_rate_medio\nFROM download d\nJOIN client c ON d.client_ip = c.client_ip\nWHERE $__timeFilter(d.test_time)\n    AND d.loss_rate >= 0\n    AND CASE WHEN c.asn IN ('18881', '26599', '27699', '19182', '10429') THEN 'Telefônica' WHEN c.asn IN ('28573', '4230', '22085') THEN 'Claro' WHEN c.asn IN ('265303') THEN 'TV Alphaville' WHEN c.asn IN ('14868') THEN 'COPEL Telecom' WHEN c.asn IN ('53184') THEN 'INB Telecom' WHEN c.asn IN ('262907') THEN 'Avato Tecnologia' WHEN c.asn IN ('61844') THEN 'New Master' WHEN c.asn IN ('28258') THEN 'Powerline Internet' WHEN c.asn IN ('273683') THEN 'Desconhecido' WHEN c.asn IN ('22689') THEN 'Sercomtel' WHEN c.asn IN ('53062') THEN 'G G Net' WHEN c.asn IN ('264228') THEN 'Brasil Starlink' WHEN c.asn IN ('28669') THEN 'America Net' WHEN c.asn IN ('263645') THEN 'Fixtell Telecom' WHEN c.asn IN ('266949') THEN 'Divifibra' WHEN c.asn IN ('262700') THEN 'Efibra Telecom' WHEN c.asn IN ('28658') THEN 'Gigalink' WHEN c.asn IN ('262673') THEN 'Lafaiete' WHEN c.asn IN ('52900') THEN 'Quality Telecom' WHEN c.asn IN ('263629') THEN 'Celloni' WHEN c.asn IN ('52940') THEN 'Nemesis' WHEN c.asn IN ('262671') THEN 'S & M Informática' WHEN c.asn IN ('28241') THEN 'Viaceu Internet' WHEN c.asn IN ('53191') THEN 'Plug Telecom' WHEN c.asn IN ('28263') THEN 'Ensite Brasil' WHEN c.asn IN ('263072') THEN 'BD Fibra Telecom' WHEN c.asn IN ('53171') THEN 'Omni Telecom' ELSE c.as_name END IN ($isp)\n    AND d.server_site IN ($server)\nGROUP BY provedor\nORDER BY loss_rate_medio ASC",
     "selectedFormat": 2
    }
   ]
  },
  {
   "title": "Total de Testes por Provedor",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT\n    CASE\n        WHEN c.asn IN ('18881', '26599', '27699', '19182', '10429') THEN 'Telefônica'\n        WHEN c.asn IN ('28573', '4230', '22085') THEN 'Claro'\n        WHEN c.asn IN ('265303') THEN 'TV Alphaville'\n        WHEN c.asn IN ('14868') THEN 'COPEL Telecom'\n        WHEN c.asn IN ('53184') THEN 'INB Telecom'\n        WHEN c.asn IN ('262907') THEN 'Avato Tecnologia'\n        WHEN c.asn IN ('61844') THEN 'New Master'\n        WHEN c.asn IN ('28258') THEN 'Powerline Internet'\n        WHEN c.asn IN ('273683') THEN 'Desconhecido'\n        WHEN c.asn IN ('22689') THEN 'Sercomtel'\n        WHEN c.asn IN ('53062') THEN 'G G Net'\n        WHEN c.asn IN ('264228') THEN 'Brasil Starlink'\n        WHEN c.asn IN ('28669') THEN 'America Net'\n        WHEN c.asn IN ('263645') THEN 'Fixtell Telecom'\n        WHEN c.asn IN ('266949') THEN 'Divifibra'\n        WHEN c.asn IN ('262700') THEN 'Efibra Telecom'\n        WHEN c.asn IN ('28658') THEN 'Gigalink'\n        WHEN c.asn IN ('262673') THEN 'Lafaiete'\n        WHEN c.asn IN ('52900') THEN 'Quality Telecom'\n        WHEN c.asn IN ('263629') THEN 'Celloni'\n        WHEN c.asn IN ('52940') THEN 'Nemesis'\n        WHEN c.asn IN ('262671') THEN 'S & M Informática'\n        WHEN c.asn IN ('28241') THEN 'Viaceu Internet'\n        WHEN c.asn IN ('53191') THEN 'Plug Telecom'\n        WHEN c.asn IN ('28263') THEN 'Ensite Brasil'\n        WHEN c.asn IN ('263072') THEN 'BD Fibra Telecom'\n        WHEN c.asn IN ('53171') THEN 'Omni Telecom'\n        ELSE c.as_name\n    END AS provedor,\n    count() AS total_testes\nFROM download d\nJOIN client c ON d.client_ip = c.client_ip\nWHERE $__timeFilter(d.test_time)\n    AND CASE WHEN c.asn IN ('18881', '26599', '27699', '19182', '10429') THEN 'Telefônica' WHEN c.asn IN ('28573', '4230', '22085') THEN 'Claro' WHEN c.asn IN ('265303') THEN 'TV Alphaville' WHEN c.asn IN ('14868') THEN 'COPEL Telecom' WHEN c.asn IN ('53184') THEN 'INB Telecom' WHEN c.asn IN ('262907') THEN 'Avato Tecnologia' WHEN c.asn IN ('61844') THEN 'New Master' WHEN c.asn IN ('28258') THEN 'Powerline Internet' WHEN c.asn IN ('273683') THEN 'Desconhecido' WHEN c.asn IN ('22689') THEN 'Sercomtel' WHEN c.asn IN ('53062') THEN 'G G Net' WHEN c.asn IN ('264228') THEN 'Brasil Starlink' WHEN c.asn IN ('28669') THEN 'America Net' WHEN c.asn IN ('263645') THEN 'Fixtell Telecom' WHEN c.asn IN ('266949') THEN 'Divifibra' WHEN c.asn IN ('262700') THEN 'Efibra Telecom' WHEN c.asn IN ('28658') THEN 'Gigalink' WHEN c.asn IN ('262673') THEN 'Lafaiete' WHEN c.asn IN ('52900') THEN 'Quality Telecom' WHEN c.asn IN ('263629') THEN 'Celloni' WHEN c.asn IN ('52940') THEN 'Nemesis' WHEN c.asn IN ('262671') THEN 'S & M Informática' WHEN c.asn IN ('28241') THEN 'Viaceu Internet' WHEN c.asn IN ('53191') THEN 'Plug Telecom' WHEN c.asn IN ('28263') THEN 'Ensite Brasil' WHEN c.asn IN ('263072') THEN 'BD Fibra Telecom' WHEN c.asn IN ('53171') THEN 'Omni Telecom' ELSE c.as_name END IN ($isp)\n    AND d.server_site IN ($server)\nGROUP BY provedor\nORDER BY total_testes DESC",
     "selectedFormat": 2
    }
   ]
  }
 ]
}