{
 "title": "NDT Dashboard - Parte 1: Visão Geral",
 "tags": [
  "ndt",
  "questdb"
 ],
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "isp",
    "label": "ISP",
    "query": "SELECT DISTINCT\n    CASE\n        WHEN asn IN ('18881', '26599', '27699', '19182', '10429') THEN 'Telefônica'\n        WHEN asn IN ('28573', '4230', '22085') THEN 'Claro'\n        WHEN asn IN ('265303') THEN 'TV Alphaville'\n        WHEN asn IN ('14868') THEN 'COPEL Telecom'\n        WHEN asn IN ('53184') THEN 'INB Telecom'\n        WHEN asn IN ('262907') THEN 'Avato Tecnologia'\n        WHEN asn IN ('61844') THEN 'New Master'\n        WHEN asn IN ('28258') THEN 'Powerline Internet'\n        WHEN asn IN ('273683') THEN 'Desconhecido'\n        WHEN asn IN ('22689') THEN 'Sercomtel'\n        WHEN asn IN ('53062') THEN 'G G Net'\n        WHEN asn IN ('264228') THEN 'Brasil Starlink'\n        WHEN asn IN ('28669') THEN 'America Net'\n        WHEN asn IN ('263645') THEN 'Fixtell Telecom'\n        WHEN asn IN ('266949') THEN 'Divifibra'\n        WHEN asn IN ('262700') THEN 'Efibra Telecom'\n        WHEN asn IN ('28658') THEN 'Gigalink'\n        WHEN asn IN ('262673') THEN 'Lafaiete'\n        WHEN asn IN ('52900') THEN 'Quality Telecom'\n        WHEN asn IN ('263629') THEN 'Celloni'\n        WHEN asn IN ('52940') THEN 'Nemesis'\n        WHEN asn IN ('262671') THEN 'S & M Informática'\n        WHEN asn IN ('28241') THEN 'Viaceu Internet'\n        WHEN asn IN ('53191') THEN 'Plug Telecom'\n        WHEN asn IN ('28263') THEN 'Ensite Brasil'\n        WHEN asn IN ('263072') THEN 'BD Fibra Telecom'\n        WHEN asn IN ('53171') THEN 'Omni Telecom'\n        ELSE as_name\n    END AS __text,\n    CASE\n        WHEN asn IN ('18881', '26599', '27699', '19182', '10429') THEN 'Telefônica'\n        WHEN asn IN ('28573', '4230', '22085') THEN 'Claro'\n        WHEN asn IN ('265303') THEN 'TV Alphaville'\n        WHEN asn IN ('14868') THEN 'COPEL Telecom'\n        WHEN asn IN ('53184') THEN 'INB Telecom'\n        WHEN asn IN ('262907') THEN 'Avato Tecnologia'\n        WHEN asn IN ('61844') THEN 'New Master'\n        WHEN asn IN ('28258') THEN 'Powerline Internet'\n        WHEN asn IN ('273683') THEN 'Desconhecido'\n        WHEN asn IN ('22689') THEN 'Sercomtel'\n        WHEN asn IN ('53062') THEN 'G G Net'\n        WHEN asn IN ('264228') THEN 'Brasil Starlink'\n        WHEN asn IN ('28669') THEN 'America Net'\n        WHEN asn IN ('263645') THEN 'Fixtell Telecom'\n        WHEN asn IN ('266949') THEN 'Divifibra'\n        WHEN asn IN ('262700') THEN 'Efibra Telecom'\n        WHEN asn IN ('28658') THEN 'Gigalink'\n        WHEN asn IN ('262673') THEN 'Lafaiete'\n        WHEN asn IN ('52900') THEN 'Quality Telecom'\n        WHEN asn IN ('263629') THEN 'Celloni'\n        WHEN asn IN ('52940') THEN 'Nemesis'\n        WHEN asn IN ('262671') THEN 'S & M Informática'\n        WHEN asn IN ('28241') THEN 'Viaceu Internet'\n        WHEN asn IN ('53191') THEN 'Plug Telecom'\n        WHEN asn IN ('28263') THEN 'Ensite Brasil'\n        WHEN asn IN ('263072') THEN 'BD Fibra Telecom'\n        WHEN asn IN ('53171') THEN 'Omni Telecom'\n        ELSE as_name\n    END AS __value\nFROM client\nORDER BY 1"
   },
   {
    "name": "server",
    "label": "Servidor",
    "query": "SELECT DISTINCT server_site AS __text, server_site AS __value\nFROM download\nWHERE server_site IS NOT NULL\nORDER BY 1"
   }
  ]
 },
 "panels": [
  {
   "title": "Total de Clientes",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(DISTINCT d.client_ip) AS total_clientes\nFROM download d\nJOIN client c ON d.client_ip = c.client_ip\nWHERE $__timeFilter(d.test_time)\n    AND CASE\n        WHEN c.asn IN ('18881', '26599', '27699', '19182', '10429') THEN 'Telefônica'\n        WHEN c.asn IN ('28573', '4230', '22085') THEN 'Claro'\n        WHEN c.asn IN ('265303') THEN 'TV Alphaville'\n        WHEN c.asn IN ('14868') THEN 'COPEL Telecom'\n        WHEN c.asn IN ('53184') THEN 'INB Telecom'\n        WHEN c.asn IN ('262907') THEN 'Avato Tecnologia'\n        WHEN c.asn IN ('61844') THEN 'New Master'\n        WHEN c.asn IN ('28258') THEN 'Powerline Internet'\n        WHEN c.asn IN ('273683') THEN 'Desconhecido'\n        WHEN c.asn IN ('22689') THEN 'Sercomtel'\n        WHEN c.asn IN ('53062') THEN 'G G Net'\n        WHEN c.asn IN ('264228') THEN 'Brasil Starlink'\n        WHEN c.asn IN ('28669') THEN 'America Net'\n        WHEN c.asn IN ('263645') THEN 'Fixtell Telecom'\n        WHEN c.asn IN ('266949') THEN 'Divifibra'\n        WHEN c.asn IN ('262700') THEN 'Efibra Telecom'\n        WHEN c.asn IN ('28658') THEN 'Gigalink'\n        WHEN c.asn IN ('262673') THEN 'Lafaiete'\n        WHEN c.asn IN ('52900') THEN 'Quality Telecom'\n        WHEN c.asn IN ('263629') THEN 'Celloni'\n        WHEN c.asn IN ('52940') THEN 'Nemesis'\n        WHEN c.asn IN ('262671') THEN 'S & M Informática'\n        WHEN c.asn IN ('28241') THEN 'Viaceu Internet'\n        WHEN c.asn IN ('53191') THEN 'Plug Telecom'\n        WHEN c.asn IN ('28263') THEN 'Ensite Brasil'\n        WHEN c.asn IN ('263072') THEN 'BD Fibra Telecom'\n        WHEN c.asn IN ('53171') THEN 'Omni Telecom'\n        ELSE c.as_name\n    END IN ($isp)",
     "selectedFormat": 2
    }
   ]
  },
  {
   "title": "Total de Servidores",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(DISTINCT server_ip) AS total_servidores\nFROM server",
     "selectedFormat": 2
    }
   ]
  },
  {
   "title": "Total de Testes",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count() AS total_testes\nFROM download d\nJOIN client c ON d.client_ip = c.client_ip\nWHERE $__timeFilter(d.test_time)\n    AND CASE\n        WHEN c.asn IN ('18881', '26599', '27699', '19182', '10429') THEN 'Telefônica'\n        WHEN c.asn IN ('28573', '4230', '22085') THEN 'Claro'\n        WHEN c.asn IN ('265303') THEN 'TV Alphaville'\n        WHEN c.asn IN ('14868') THEN 'COPEL Telecom'\n        WHEN c.asn IN ('53184') THEN 'INB Telecom'\n        WHEN c.asn IN ('262907') THEN 'Avato Tecnologia'\n        WHEN c.asn IN ('61844') THEN 'New Master'\n        WHEN c.asn IN ('28258') THEN 'Powerline Internet'\n        WHEN c.asn IN ('273683') THEN 'Desconhecido'\n        WHEN c.asn IN ('22689') THEN 'Sercomtel'\n        WHEN c.asn IN ('53062') THEN 'G G Net'\n        WHEN c.asn IN ('264228') THEN 'Brasil Starlink'\n        WHEN c.asn IN ('28669') THEN 'America Net'\n        WHEN c.asn IN ('263645') THEN 'Fixtell Telecom'\n        WHEN c.asn IN ('266949') THEN 'Divifibra'\n        WHEN c.asn IN ('262700') THEN 'Efibra Telecom'\n        WHEN c.asn IN ('28658') THEN 'Gigalink'\n        WHEN c.asn IN ('262673') THEN 'Lafaiete'\n        WHEN c.asn IN ('52900') THEN 'Quality Telecom'\n        WHEN c.asn IN ('263629') THEN 'Celloni'\n        WHEN c.asn IN ('52940') THEN 'Nemesis'\n        WHEN c.asn IN ('262671') THEN 'S & M Informática'\n        WHEN c.asn IN ('28241') THEN 'Viaceu Internet'\n        WHEN c.asn IN ('53191') THEN 'Plug Telecom'\n        WHEN c.asn IN ('28263') THEN 'Ensite Brasil'\n        WHEN c.asn IN ('263072') THEN 'BD Fibra Telecom'\n        WHEN c.asn IN ('53171') THEN 'Omni Telecom'\n        ELSE c.as_name\n    END IN ($isp)",
     "selectedFormat": 2
    }
   ]
  },
  {
   "title": "Clientes por Provedor",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "rawSql": "SELECT\n    CASE\n        WHEN c.asn IN ('18881', '26599', '27699', '19182', '10429') THEN 'Telefônica'\n        WHEN c.asn IN ('28573', '4230', '22085') THEN 'Claro'\n        WHEN c.asn IN ('265303') THEN 'TV Alphaville'\n        WHEN c.asn IN ('14868') THEN 'COPEL Telecom'\n        WHEN c.asn IN ('53184') THEN 'INB Telecom'\n        WHEN c.asn IN ('262907') THEN 'Avato Tecnologia'\n        WHEN c.asn IN ('61844') THEN 'New Master'\n        WHEN c.asn IN ('28258') THEN 'Powerline Internet'\n        WHEN c.asn IN ('273683') THEN 'Desconhecido'\n        WHEN c.asn IN ('22689') THEN 'Sercomtel'\n        WHEN c.asn IN ('53062') THEN 'G G Net'\n        WHEN c.asn IN ('264228') THEN 'Brasil Starlink'\n        WHEN c.asn IN ('28669') THEN 'America Net'\n        WHEN c.asn IN ('263645') THEN 'Fixtell Telecom'\n        WHEN c.asn IN ('266949') THEN 'Divifibra'\n        WHEN c.asn IN ('262700') THEN 'Efibra Telecom'\n        WHEN c.asn IN ('28658') THEN 'Gigalink'\n        WHEN c.asn IN ('262673') THEN 'Lafaiete'\n        WHEN c.asn IN ('52900') THEN 'Quality Telecom'\n        WHEN c.asn IN ('263629') THEN 'Celloni'\n        WHEN c.asn IN ('52940') THEN 'Nemesis'\n        WHEN c.asn IN ('262671') THEN 'S & M Informática'\n        WHEN c.asn IN ('28241') THEN 'Viaceu Internet'\n        WHEN c.asn IN ('53191') THEN 'Plug Telecom'\n        WHEN c.asn IN ('28263') THEN 'Ensite Brasil'\n        WHEN c.asn IN ('263072') THEN 'BD Fibra Telecom'\n        WHEN c.asn IN ('53171') THEN 'Omni Telecom'\n        ELSE c.as_name\n    END AS provedor,\n    count(DISTINCT d.client_ip) AS total_clientes\nFROM download d\nJOIN client c ON d.client_ip = c.client_ip\nWHERE $__timeFilter(d.test_time)\n    AND CASE\n        WHEN c.asn IN ('18881', '26599', '27699', '19182', '10429') THEN 'Telefônica'\n        WHEN c.asn IN ('28573', '4230', '22085') THEN 'Claro'\n        WHEN c.asn IN ('265303') THEN 'TV Alphaville'\n        WHEN c.asn IN ('14868') THEN 'COPEL Telecom'\n        WHEN c.asn IN ('53184') THEN 'INB Telecom'\n        WHEN c.asn IN ('262907') THEN 'Avato Tecnologia'\n        WHEN c.asn IN ('61844') THEN 'New Master'\n        WHEN c.asn IN ('28258') THEN 'Powerline Internet'\n        WHEN c.asn IN ('273683') THEN 'Desconhecido'\n        WHEN c.asn IN ('22689') THEN 'Sercomtel'\n        WHEN c.asn IN ('53062') THEN 'G G Net'\n        WHEN c.asn IN ('264228') THEN 'Brasil Starlink'\n        WHEN c.asn IN ('28669') THEN 'America Net'\n        WHEN c.asn IN ('263645') THEN 'Fixtell Telecom'\n        WHEN c.asn IN ('266949') THEN 'Divifibra'\n        WHEN c.asn IN ('262700') THEN 'Efibra Telecom'\n        WHEN c.asn IN ('28658') THEN 'Gigalink'\n        WHEN c.asn IN ('262673') THEN 'Lafaiete'\n        WHEN c.asn IN ('52900') THEN 'Quality Telecom'\n        WHEN c.asn IN ('263629') THEN 'Celloni'\n        WHEN c.asn IN ('52940') THEN 'Nemesis'\n        WHEN c.asn IN ('262671') THEN 'S & M Informática'\n        WHEN c.asn IN ('28241') THEN 'Viaceu Internet'\n        WHEN c.asn IN ('53191') THEN 'Plug Telecom'\n        WHEN c.asn IN ('28263') THEN 'Ensite Brasil'\n        WHEN c.asn IN ('263072') THEN 'BD Fibra Telecom'\n        WHEN c.asn IN ('53171') THEN 'Omni Telecom'\n        ELSE c.as_name\n    END IN ($isp)\nGROUP BY provedor\nORDER BY total_clientes DESC\nLIMIT 6",
     "selectedFormat": 2
    }
   ]
  },
  {
   "title": "Mapa Clientes por Cidade e Servidor",
   "type": "geomap",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT\n    c.latitude AS lat,\n    c.longitude AS lon,\n    c.city,\n    c.country_name,\n    d.server_site,\n    count() AS total_testes,\n    count(DISTINCT d.client_ip) AS clientes_unicos\nFROM download d\nJOIN client c ON d.client_ip = c.client_ip\nWHERE $__timeFilter(d.test_time)\n    AND c.country_code = 'BR'\n    AND CASE\n        WHEN c.asn IN ('18881', '26599', '27699', '19182', '10429') THEN 'Telefônica'\n        WHEN c.asn IN ('28573', '4230', '22085') THEN 'Claro'\n        WHEN c.asn IN ('265303') THEN 'TV Alphaville'\n        WHEN c.asn IN ('14868') THEN 'COPEL Telecom'\n        WHEN c.asn IN ('53184') THEN 'INB Telecom'\n        WHEN c.asn IN ('262907') THEN 'Avato Tecnologia'\n        WHEN c.asn IN ('61844') THEN 'New Master'\n        WHEN c.asn IN ('28258') THEN 'Powerline Internet'\n        WHEN c.asn IN ('273683') THEN 'Desconhecido'\n        WHEN c.asn IN ('22689') THEN 'Sercomtel'\n        WHEN c.asn IN ('53062') THEN 'G G Net'\n        WHEN c.asn IN ('264228') THEN 'Brasil Starlink'\n        WHEN c.asn IN ('28669') THEN 'America Net'\n        WHEN c.asn IN ('263645') THEN 'Fixtell Telecom'\n        WHEN c.asn IN ('266949') THEN 'Divifibra'\n        WHEN c.asn IN ('262700') THEN 'Efibra Telecom'\n        WHEN c.asn IN ('28658') THEN 'Gigalink'\n        WHEN c.asn IN ('262673') THEN 'Lafaiete'\n        WHEN c.asn IN ('52900') THEN 'Quality Telecom'\n        WHEN c.asn IN ('263629') THEN 'Celloni'\n        WHEN c.asn IN ('52940') THEN 'Nemesis'\n        WHEN c.asn IN ('262671') THEN 'S & M Informática'\n        WHEN c.asn IN ('28241') THEN 'Viaceu Internet'\n        WHEN c.asn IN ('53191') THEN 'Plug Telecom'\n        WHEN c.asn IN ('28263') THEN 'Ensite Brasil'\n        WHEN c.asn IN ('263072') THEN 'BD Fibra Telecom'\n        WHEN c.asn IN ('53171') THEN 'Omni Telecom'\n        ELSE c.as_name\n    END IN ($isp)\n    AND c.latitude IS NOT NULL\n    AND c.longitude IS NOT NULL\nGROUP BY c.latitude, c.longitude, c.city, c.country_name, d.server_site",
     "selectedFormat": 2
    }
   ]
  }
 ]
}