{
 "title": "Relação geográfica servidores",
 "tags": [
  "ndt",
  "questdb",
  "mapa"
 ],
 "time": { "from": "now-90d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "isp",
    "label": "ISP",
    "query": "SELECT ASN_owner AS __text, ASN_owner AS __value\nFROM ASNS\nWHERE ASN_owner IS NOT NULL AND ASN_owner != ''\nGROUP BY ASN_owner\nORDER BY ASN_owner"
   },
   {
    "name": "server",
    "label": "Servidor",
    "query": "SELECT DISTINCT server_site AS __text, server_site AS __value\nFROM download\nWHERE server_site IS NOT NULL\nORDER BY 1"
   },
   {
    "name": "cidade",
    "label": "cidade",
    "query": "SELECT DISTINCT client_city AS __text, client_city AS __value\nFROM download\nWHERE client_country_code = 'BR'\nAND client_city IS NOT NULL\nORDER BY 1"
   }
  ]
 },
 "panels": [
  {
   "title": "Mapa Cliente→Servidor",
   "type": "geomap",
   "gridPos": { "h": 14, "w": 13, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n    CAST(avg(d.client_latitude) AS DOUBLE) AS lat,\n    CAST(avg(d.client_longitude) AS DOUBLE) AS lon,\n    d.client_city,\n    d.client_country_code,\n    d.server_site,\n    count() AS total_testes\nFROM download d\nLEFT JOIN ASNS a ON d.client_asn = a.ASN\nWHERE $__timeFilter(d.test_time)\n    AND d.server_site = '$server'\n    AND d.client_country_code = 'BR'\n    AND COALESCE(a.ASN_owner, d.client_asname, 'Desconhecido') IN ($isp)\n    AND d.client_latitude IS NOT NULL\n    AND d.client_longitude IS NOT NULL\nGROUP BY d.client_city, d.client_country_code, d.server_site\nlimit 2000",
     "selectedFormat": 1
    },
    {
     "rawSql": "SELECT\n    CAST(latitude AS DOUBLE) AS lat,\n    CAST(longitude AS DOUBLE) AS lon,\n    site AS server_site,\n    city,\n    country_name\nFROM server\nWHERE site = '$server'\n    AND latitude IS NOT NULL\n    AND longitude IS NOT NULL",
     "selectedFormat": 1
    }
   ]
  },
  {
   "title": "Localização dos servidores",
   "type": "geomap",
   "gridPos": { "h": 14, "w": 11, "x": 13, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n    CAST(latitude AS DOUBLE) AS lat,\n    CAST(longitude AS DOUBLE) AS lon,\n    site AS server_site,\n    city,\n    country_name,\n    country_code,\n    machine_type,\n    machine_zone\nFROM server\nWHERE latitude IS NOT NULL\n    AND longitude IS NOT NULL\n    AND site IN (SELECT DISTINCT server_site FROM download WHERE server_site IS NOT NULL LIMIT 1000)",
     "selectedFormat": 2
    }
   ]
  },
  {
   "title": "Top 10 Cidades — Servidor",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "rawSql": "SELECT\n    d.client_city AS cidade,\n    count() AS total_testes,\n    count(DISTINCT d.client_ip) AS clientes_unicos\nFROM download d\nLEFT JOIN ASNS a ON d.client_asn = a.ASN\nWHERE $__timeFilter(d.test_time)\n    AND d.server_site = '$server'\n    AND d.client_country_code = 'BR'\n    AND COALESCE(a.ASN_owner, d.client_asname, 'Desconhecido') IN ($isp)\nGROUP BY d.client_city\nORDER BY total_testes DESC\nLIMIT 10",
     "selectedFormat": 2
    }
   ]
  },
  {
   "title": "Dispersão de servidores por cidade",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "targets": [
    {
     "rawSql": "SELECT\n    d.server_site AS servidor,\n    count() AS total_testes\nFROM download d\nLEFT JOIN ASNS a ON d.client_asn = a.ASN\nWHERE $__timeFilter(d.test_time)\n    AND d.client_country_code = 'BR'\n    AND COALESCE(a.ASN_owner, d.client_asname, 'Desconhecido') IN ($isp)\n    AND d.client_city = '$cidade'\nGROUP BY d.server_site\nORDER BY total_testes DESC\nLIMIT 10",
     "selectedFormat": 2
    }
   ]
  },
  {
   "title": "Servidores usados em um cidade",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "targets": [
    {
     "rawSql": "SELECT\n    d.server_site AS servidor,\n    count() AS total_testes,\n    count(DISTINCT d.client_ip) AS clientes_unicos\nFROM download d\nLEFT JOIN ASNS a ON d.client_asn = a.ASN\nWHERE $__timeFilter(d.test_time)\n    AND d.client_country_code = 'BR'\n    AND COALESCE(a.ASN_owner, d.client_asname, 'Desconhecido') IN ($isp)\n    AND d.client_city = '$cidade'\nGROUP BY d.server_site\nORDER BY total_testes DESC\nLIMIT 10",
     "selectedFormat": 2
    }
   ]
  },
  {
   "title": " Servidores por provedor",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "targets": [
    {
     "rawSql": "SELECT\n    d.server_site AS servidor,\n    count() AS total_testes,\n    count(DISTINCT d.client_ip) AS clientes_unicos\nFROM download d\nLEFT JOIN ASNS a ON d.client_asn = a.ASN\nWHERE $__timeFilter(d.test_time)\n    AND d.client_country_code = 'BR'\n    AND COALESCE(a.ASN_owner, d.client_asname, 'Desconhecido') IN ('Claro', 'Telefônica', 'Gigalink')\nGROUP BY d.server_site\nORDER BY total_testes DESC\nLIMIT 10",
     "selectedFormat": 2
    }
   ]
  },
  {
   "title": "Cidades por provedor",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "targets": [
    {
     "rawSql": "SELECT\n    d.client_city AS cidade,\n    count() AS total_testes,\n    count(DISTINCT d.client_ip) AS clientes_unicos\nFROM download d\nLEFT JOIN ASNS a ON d.client_asn = a.ASN\nWHERE $__timeFilter(d.test_time)\n    AND d.client_country_code = 'BR'\n    AND COALESCE(a.ASN_owner, d.client_asname, 'Desconhecido') IN ('Claro', 'Telefônica', 'Gigalink')\nGROUP BY d.client_city\nORDER BY total_testes DESC\nLIMIT 6",
     "selectedFormat": 2
    }
   ]
  }
 ]
}